mbta/lamp

- py_gtfs_rt_ingestion/batch_files.py
- py_gtfs_rt_ingestion/ingest.py
- py_gtfs_rt_ingestion/py_gtfs_rt_ingestion/batcher.py
- py_gtfs_rt_ingestion/py_gtfs_rt_ingestion/config_base.py
- py_gtfs_rt_ingestion/py_gtfs_rt_ingestion/configuration.py
- py_gtfs_rt_ingestion/py_gtfs_rt_ingestion/convert.py
- py_gtfs_rt_ingestion/py_gtfs_rt_ingestion/error.py
- py_gtfs_rt_ingestion/py_gtfs_rt_ingestion/s3_utils.py
- py_gtfs_rt_ingestion/tests/test_configuration.py
Add a file of custom library exceptions called error.py. It will contain
a base class for our custom errors and specific ones that inherit from
it. Use them where appropriate around the library.
Add logging to the library, replacing any print statements and ensure
that it is used at the info level in the two main scripts.
> Add Error Handling and Logging

- .gitignore
- py_gtfs_rt_ingestion/poetry.lock
- py_gtfs_rt_ingestion/pyproject.toml
- py_gtfs_rt_ingestion/tests/test_convert.py
Pandas added to project as Poetry dev dependency.
Additional file detail checks added to `test_convert.py`
- numpy dataframe shape
- nan value count for each data column
- dtype check for each data column
- min value check for each data column (if possible)
- max value check for each data column (if possible)
> Add Pandas for Testing

- py_gtfs_rt_ingestion/batch_files.py
- py_gtfs_rt_ingestion/ingest.py
- py_gtfs_rt_ingestion/py_gtfs_rt_ingestion/__init__.py
- py_gtfs_rt_ingestion/py_gtfs_rt_ingestion/batcher.py
- py_gtfs_rt_ingestion/py_gtfs_rt_ingestion/convert.py
- py_gtfs_rt_ingestion/tests/test_convert.py
The main goal of this PR is to convert all filehandling in `convert.py` to pyarrow FileSystem interface.
- `s3_to_pyarrow` function rolled into `gz_to_pyarrow` function.
- `batcher.py` modified to store s3 bucket name in filename path.
- added some NamedTuple classes to handle parsed arguments in `batch_files.py` and `ingest.py`
- fixed a few typos
> Perform all file reads with pyarrow.

- .github/actions/deploy/action.yaml
- .github/actions/deps/action.yaml
- .github/actions/tools/action.yaml
- .github/workflows/ci.yaml
- .github/workflows/deploy-dev.yaml
- py_gtfs_rt_ingestion/poetry.lock
- py_gtfs_rt_ingestion/pyproject.toml
- re-configures the `.github` folder to separate `workflows` and `actions`
- create `deploy` action (to be used with prod and dev)
- move poetry installs into `deps` action
- move asdf installs into `tools` action
- add `deploy-dev` to `workflows` for deploying lambda function aws dev environment
- modify `ci` in `workflows` to incorporate using actions 
TO DO:
- get `devops` PR #436 merged to provide github actions AWS credentials
> Implement CD for AWS lambda functions with github actions

- .github/pull_request_template.md
- .github/workflows/asana-pr-merged.yml
- .github/workflows/asana-pr-opened.yml
Ticket Move Action Rules:
* Move tickets to "In Review" section of a board when pull requests are
opened.
* Move tickets to "Done" section of a board and mark complete when
merged.
* Move tickets to "To Do" section of a board when pull requests are
closed.
Add a Pull Request Template that will be used when making prs.
Asana Task: https://app.asana.com/0/1202413225616890/1202368903376392/f
> Add Asana / Github Actions to move Tickets

- py_gtfs_rt_ingestion/batch_files.py
Asana Task: https://app.asana.com/0/1202413225616890/1202464608350251
Change `IMPORT_BUCKET` to `INGEST_BUCKET` in `batch_files.py` to match terraform config.
> change `IMPORT_BUCKET` to `INGEST_BUCKET`

- .tool-versions
Asana Task: https://app.asana.com/0/1202535370823256/1202604738421231
> update poetry to version 1.1.14

- py_gtfs_rt_ingestion/py_gtfs_rt_ingestion/s3_utils.py
Using a boto3 client to execute s3 file moves runs into backend race
conditions that were throwing exceptions. To avoid this, the s3 file
moving utility now uses a new Session for each move and gets a resource
from that session.
> Use Boto3 Sessions for Threading S3 File Moves

- performance_manager/lib/__init__.py
- performance_manager/lib/postgres_utils.py
- performance_manager/lib/rt_vehicle_positions.py
- performance_manager/lib/s3_utils.py
- performance_manager/load_vp_events.py
Workflow for this script is the following:
- check `metadataLog` table for paths to process
- group paths by same hourly folder
- process each group of paths in an hourly folder
- INSERT/UPDATE/DELETE event records in `eventsVehiclePositions` table
- if successful, UPDATE `processed' flag for paths in `metadataLog` table
Asana Task: https://app.asana.com/0/1202672148025243/1202784843755687
> new script to load `VEHICLE_POSITION` events to db

- .github/actions/lambda_deploy/action.yaml
- py_gtfs_rt_ingestion/batch_files.py
- py_gtfs_rt_ingestion/py_gtfs_rt_ingestion/__init__.py
- py_gtfs_rt_ingestion/py_gtfs_rt_ingestion/postgres_utils.py
Infra has added an IAM user that we can use to connect to our database
from inside the ECS container and Lambda functions. Get the token for
this user and use it to make a connection to the RDS.
* update lambda deploy action to install the ssl cert into the zip file
* add logic to batching lambda to debug connection issues
Asana Task: <asana_ticket_url>
> Generate DB Auth Tokens for AWS RDS Connections

- .github/actions/lambda_deploy/action.yaml
- py_gtfs_rt_ingestion/py_gtfs_rt_ingestion/postgres_utils.py
Finally getting connection from Lambda Functions to Performance Manager RDS.
* Update lambda deploy action to install ssl cert using curl and putting it in the zip file. Access it correctly in postgres_utils dot py if there is no password in the environment.
* Update psycopg build, taking it from a gitlab repo for now (still need to figure out how to build it ourselves)
* Properly connect to the RDS in postgres_utils dot py.
Asana Task: https://app.asana.com/0/0/1202708844890309/f
> Update psycopg2 connection methods

- performance_manager/lib/__init__.py
- performance_manager/lib/gtfs_static_table.py
- performance_manager/lib/l1_full_trip_events.py
- performance_manager/lib/logging_utils.py
- performance_manager/lib/postgres_utils.py
- performance_manager/lib/rt_trip_updates.py
- performance_manager/lib/rt_vehicle_positions.py
- performance_manager/lib/s3_utils.py
- performance_manager/pyproject.toml
- performance_manager/startup.py
- py_gtfs_rt_ingestion/py_gtfs_rt_ingestion/logging_utils.py
* Copy logging utils into performance manager library
* Use ProcessLogger throughout performance manager
* Stop allowing `e` to be a variable name. Use `exception` instead.
Asana Task: https://app.asana.com/0/1202841571879768/1202940849760974/f
> Update Logging on ECS Container

- Dockerfile
- docker-compose.yml
- performance_manager/lib/postgres_utils.py
- performance_manager/startup.py
* Add ssl cert to docker container using curl
* update postgres utils to connect to the remote rds if unable to find a password in the environment variables
* Add logging, but not re throwing if unable to find .env file in startup.
* Move command for running startup.py from docker-compose to dockerfile.
* Move verbose logging of sqlalchemy into cli args.
* Move db seeding to DBManager constructor from main method of startup dot py.
Asana Task: <asana_ticket_url>
> Add connection to PM's AWS RDS instance

- performance_manager/lib/rt_trip_updates.py
trip update processing previously utilized the pandas apply method to explode and unwrap trip updates dataframe
using the numpy vectorize feature is a significant performance improvement over pandas apply (over 50% faster)
Asana Task: https://app.asana.com/0/1202841571879768/1203021761496489
> Vectorize Trip Updates explode

- performance_manager/lib/__init__.py
- performance_manager/lib/l2_dwell_travel_times.py
- performance_manager/lib/postgres_schema.py
- performance_manager/startup.py
This commit adds schema and logic for dwell and travel times
These two tables are grouped together because the logic behind them is the same, the only difference being dwell times deals with stopped events and travel times deals with moving events
Asana Task: https://app.asana.com/0/1202841571879768/1202672148025254
> Dwell & Travel time tables

- performance_manager/lib/rt_trip_updates.py
- performance_manager/lib/s3_utils.py
processing of trip update parquet files was resulting in very high memory usage. this commit adds batching to the processing of trip update parquet files to limit memory usage.
`read_parquet_chunks` function added to `s3_utils.py`. this function defaults to reading ~100,000 rows from a parquet at a time.
Asana Task: https://app.asana.com/0/1202841571879768/1203021761496491
> add batching to trip update processing

- .github/workflows/ingestion-deploy-dev.yaml
- .github/workflows/performance-manager-deploy-dev.yaml
- py_gtfs_rt_ingestion/poetry.lock
- py_gtfs_rt_ingestion/pyproject.toml
A handful of small deployment issues are fixed here. This PR should be rebased before merging.
> Deployment debugging

- py_gtfs_rt_ingestion/ingest.py
we turned it off to reset our rds. now turn it back on.
> turn ingestion back on

- performance_manager/lib/rt_trip_updates.py
- py_gtfs_rt_ingestion/ingest.py
- py_gtfs_rt_ingestion/lib/convert_gtfs.py
- py_gtfs_rt_ingestion/lib/postgres_utils.py
- py_gtfs_rt_ingestion/lib/s3_utils.py
* skip process_trip_updates if no new events records to prevent a key error.
* add better logging to main ingestion function.
* fix oversight by adding files to archive file list in gtfs static ingestion.
* use correct filepath for aws ssl cert file.
* wrap file_list_from_s3 in a try/except block.
> Deployment Fixes

- py_gtfs_rt_ingestion/lib/s3_utils.py
This PR is meant to speed up s3 file move operations in the ECS instance. 
Performance improvement is achieved with 2 main changes:
1. Switch from Threading to Multi-Processing
-- Threading was previously required because lambda instances did not support multi-processing. Multi-processing processes are slightly more expensive to create, but more performant during run-time than threads. 
2. Use shared boto session object for each process. 
-- Creating boto Session objects for every file move operation is very expensive for the number of file moves we are completing. Using the multi-processing Pool `initializer` keyword argument, we are able to create a Session at process initialization and use it for all move operations done during the life of the process. 
In my testing this update showed …
> Improve speed of S3 file move operations

- py_gtfs_rt_ingestion/ingest.py
- py_gtfs_rt_ingestion/lib/__init__.py
- py_gtfs_rt_ingestion/lib/convert_gtfs.py
- py_gtfs_rt_ingestion/lib/convert_gtfs_rt.py
- py_gtfs_rt_ingestion/lib/converter.py
- py_gtfs_rt_ingestion/lib/ingest.py
- py_gtfs_rt_ingestion/lib/logging_utils.py
- py_gtfs_rt_ingestion/lib/postgres_utils.py
- py_gtfs_rt_ingestion/lib/s3_utils.py
- py_gtfs_rt_ingestion/lib/utils.py
- py_gtfs_rt_ingestion/pyproject.toml
- py_gtfs_rt_ingestion/tests/test_gtfs_converter.py
- py_gtfs_rt_ingestion/tests/test_gtfs_rt_converter.py
- py_gtfs_rt_ingestion/tests/test_ingest.py
Our ingestion was taking way too long. To speed it up, put each filetypes conversion into its own thread.
> Ingest sort group files 2

- performance_manager/Dockerfile
- performance_manager/lib/postgres_utils.py
- performance_manager/startup.py
- py_gtfs_rt_ingestion/Dockerfile
- py_gtfs_rt_ingestion/ingest.py
- py_gtfs_rt_ingestion/lib/__init__.py
- py_gtfs_rt_ingestion/lib/convert_gtfs.py
- py_gtfs_rt_ingestion/lib/convert_gtfs_rt.py
- py_gtfs_rt_ingestion/lib/converter.py
- py_gtfs_rt_ingestion/lib/gtfs_rt_detail.py
- py_gtfs_rt_ingestion/lib/ingest.py
- py_gtfs_rt_ingestion/lib/postgres_utils.py
- py_gtfs_rt_ingestion/lib/s3_utils.py
- py_gtfs_rt_ingestion/tests/test_gtfs_rt_converter.py
- py_gtfs_rt_ingestion/tests/test_ingest.py
- py_gtfs_rt_ingestion/tests/test_s3_utils.py
This PR implements changes to RDS engine creation in both applications to avoid disconnects over long running times. 
Main fix for disconnect and authentication issues is to re-generate db auth token on every new RDS pool connection refresh. 
This also implements a Queue system for writing parquet metadata information to RDS for ingestion. 
This also implements optimization to pyarrow table creation process. Table data from json files is kept in a dictionary until full table is yielding for writing, at which point it is converted to a pyarrow table. 
Asana Task: https://app.asana.com/0/1203185253920158/1203335186086560
> fix rds pool and small optimizations

- performance_manager/lib/logging_utils.py
- performance_manager/lib/postgres_utils.py
- py_gtfs_rt_ingestion/ingest.py
- py_gtfs_rt_ingestion/lib/convert_gtfs_rt.py
- py_gtfs_rt_ingestion/lib/logging_utils.py
- py_gtfs_rt_ingestion/lib/postgres_utils.py
- py_gtfs_rt_ingestion/lib/s3_utils.py
- py_gtfs_rt_ingestion/lib/utils.py
This PR is a collection of changes that I made will attempting to resolve RDS connection issues.
The main RDS connection resolution is to limit the number of connections that are being created by our database engine object. This is mostly achieved by passing specific parameters to the sqlalchemy `create_engine` function.
Various logging updates are also included to aid in splunk debugging.
Asana Task: https://app.asana.com/0/1203185253920158/1203344379200929
> Resolve RDS connection issues, again

- py_gtfs_rt_ingestion/lib/convert_gtfs_rt.py
Add try/except to `convert` for gtfs_rt
Add logging start in `process_files`
> Fix try/except in gtfs_rt convert

- .github/workflows/performance-manager-ci.yaml
- performance_manager/tests/test_postgres.py
* Add tests that create a DatabaseManager object and ensure we can connect to the database.
* Add pytest to Performance Manager CI
* Add a postgres service to the test step in Performance Manager CI
Asana Task: https://app.asana.com/0/1203100082488441/1203144932470000/f
> Add Postgres Tests to Performance Manager

- performance_manager/lib/__init__.py
- performance_manager/lib/ecs.py
- performance_manager/lib/l0_gtfs_rt_events.py
- performance_manager/lib/l0_gtfs_static_table.py
- performance_manager/startup.py
Update logging information around SQL Updates and Insertions and ensure that timestamps and pk_ids are integers.
> SQL Degradation Checks

- python_src/poetry.lock
- python_src/pyproject.toml
This fixes a SIGSEGV for @paulswartz on his M1.
> chore: update PyArrow to 11

- python_src/src/lamp_py/migrations/versions/performance_manager/2e9d81949da8_trips_and_metrics_processing_updates.py
PR #115 added the `fk_static_timstamp` column to `vehicle_trips` as a non-nullable column. However, since data already exists in the `vehicle_trips` table on the DEV RDS, creating the column automatically creates all NULL records.
This PR updates the alembic update logic to add `fk_static_timestamp` as a nullable column, populate the column from data in the vehicle_events table, and then return `fk_static_timestamp` to a non-nullable column.
> Fix Creation of `fk_static_timestamp` in vehicle_trips table

- python_src/src/lamp_py/migrations/versions/performance_manager/016_171891fde1cf_create_opmi_all_fields_view.py
Create consolidated view of RT data for OPMI tableau data pull 
Asana Task: https://app.asana.com/0/1204614792357231/1204702012699361
> feat: create `opmi_all_rt_fields_joined` view

- .github/workflows/change_ingestion_task_count.yaml
doing this as part of the staging testing effort.
> Add a github action to turn ingestion on and off

- .github/workflows/change_ingestion_task_count.yaml
* Add a job name and conditions to run the job
* Add a runs-on flag
* Echo the command before running it
> FIX: Use correct GH Action syntax in .yaml file

- .github/workflows/manual-deploy.yaml
another silly yaml mistake.
hopefully the last one for a while.
> FIX: Bad Indentation in Manual Deploy

- python_src/src/lamp_py/tableau/jobs/gtfs_rail.py
- python_src/src/lamp_py/tableau/jobs/rt_rail.py
`batch_size` parameter needs to be integer
> FIX: batch_size from float to int

- .github/dependabot.yaml
Asana Task: <https://app.asana.com/0/1189492770004753/1206094509828999/f>
add a dependabot configuration file.
> add dependabot configuration file

- python_src/src/lamp_py/aws/s3.py
The pyarrow write dataset function has shown to consume a lot of memory while also taking longer to execute. It has features we use around partitioning and file visitor functions, but those features can be replicated without too much difficulty given the way we use them.
Asana Task: https://app.asana.com/0/1205827492903547/1206273298673481/f
> Use ParquetWriter rather than Dataset.writedataset

- python_src/poetry.lock
- python_src/pyproject.toml
- python_src/src/lamp_py/performance_manager/l0_gtfs_rt_events.py
- python_src/src/lamp_py/performance_manager/l1_cte_statements.py
- python_src/src/lamp_py/performance_manager/l1_rt_metrics.py
- python_src/src/lamp_py/performance_manager/l1_rt_trips.py
- python_src/src/lamp_py/postgres/postgres_schema.py
- python_src/src/lamp_py/postgres/postgres_utils.py
- python_src/src/lamp_py/postgres/snapshot.py
Update to using SQLAlchemy 2.0
Luckily not a ton of changes required to make this update. Will hopefully result in better type-checking / linting. 
Asana Task: https://app.asana.com/0/1205827492903547/1204354793482788
> chore: Update SQLAlchemy to 2.0

- python_src/src/lamp_py/performance_manager/l0_gtfs_static_load.py
- python_src/tests/performance_manager/test_performance_manager.py
When `performance_manager` is importing a GTFS static schedule, it expects all ingested tables to contain data. Per the GTFS Spec, the `calendar_dates` table is not required to contain data. 
Out `ingestion` application manifests this as not writing any parquet file to S3 for an empty `calendar_dates` static file. `file_list_from_s3` then returns an empty list when the `CALENDAR_DATES` partition is listed for a specific static schedule. 
To fix this, we will catch a `KeyError` when converting a GTFS static parquet file into a pandas dataframe, and return an empty dateframe with all required columns, if allowed by the `allow_empty_dataframe` bool flag of the `StaticTableColumns` dataclass. 
Also added a couple tests to verify this functionality. 
Currently, two static schedule need to be …
> FIX: Allow empty `calendar_dates` GTFS static table

- poetry.lock
When I updated the pyproject.toml file I forgot to update the poetry.lock file. Do that now before it messes things up for development.
> FIX: Update poetry dot lock file

- src/lamp_py/tableau/jobs/rt_rail.py
On prod, the ECS is failing somewhere inside of the `HyperRtRail.update_parquet` function. Add extra logging so it can be monitored both on staging and (going forward) on prod.
> Add extra logging to GTFS RT Rail Parquet Creation

- src/lamp_py/performance_manager/flat_file.py
- src/lamp_py/tableau/jobs/gtfs_rail.py
- src/lamp_py/tableau/jobs/rt_rail.py
- tests/performance_manager/test_performance_manager.py
For flat files in the public archive, check the metadata for version information and overwrite files that are not using the current version of the rail performance manager. Files with mismatched versions that will not be overwritten are deleted.
Asana Task: [Add Version Metadata to Public Flat Files
](https://app.asana.com/0/1189492770004753/1206931284338815/f)
> Feat: Check Version on Public Archive Files

- .env
- Dockerfile
- README.md
- docker-compose.yml
- poetry.lock
- pyproject.toml
- src/lamp_py/mssql/__init__.py
- src/lamp_py/mssql/mssql_utils.py
- src/lamp_py/mssql/test_connect.py
This change adds the scaffolding required for our Ingestion application to make a connection to the TransitMaster Microsoft SQL Server. 
With this scaffolding we are able to use the `MSSQLManager` class to return query results as a list of dicts, pandas dataframe or write directly to a parquet file. 
Asana Task: https://app.asana.com/0/1205827492903547/1206974089170980
> FEAT: MSSQL Server Connection Scaffolding

- src/lamp_py/aws/s3.py
`file_list_from_s3_with_details()` function was limited to returning a maximum of 1000 results without a paginator. This was breaking our writing of `index.csv` for the `subway-on-time-performance-v1` data export. 
Added `paginator` to return an unlimited number of results.
> FIX: Add paginator to file_list_from_s3_with_details

- Data_Dictionary.md
OPMI requested updates to Data Dictionary definitions, made via slack on May 2 2024.
> FIX: OPMI Requsted updates to Data Dictionary May 2, 2024

- pyproject.toml
- src/lamp_py/ingestion_tm/ingest.py
- src/lamp_py/ingestion_tm/jobs/parition_table.py
- src/lamp_py/ingestion_tm/jobs/whole_table.py
- src/lamp_py/ingestion_tm/pipeline.py
- src/lamp_py/ingestion_tm/tm_export.py
- src/lamp_py/mssql/mssql_utils.py
New LAMP application for ingesting transit master tables. 
TM Ingestion Application will be schedule to run every hour, and will not operate on an event loop.
Application can create exports of whole database table files, or partition a database table into files based on a partition key. 
Inspired by Tableau HyperFile process. 
Asana Task: https://app.asana.com/0/1205827492903547/1207057651530893
> FEAT: Transit Master Ingestion Application

- src/lamp_py/aws/kinesis.py
- src/lamp_py/ingestion/glides.py
There are a few issues with glides ingestion that need to be ironed out before deploying to production.
* Operator Sign Ins had a mislabeled field that wasn't being picked up.
* Add try / except blocks and clear logging around kinesis reader and the ingest records blocks.
> FIX: Update to Glides Ingestion before Deploy

- src/lamp_py/ingestion/convert_gtfs_rt.py
- src/lamp_py/ingestion/utils.py
Staging environment threw a few errors when creating a combined dataset with miss-matched schemas.
This fix should resolve those errors.
> FIX: Intermitent schema error when joining datsets

- Data_Dictionary.md
Data Dictionary updates that were requested by Ops Analytics. 
Mix of typo fixes, and nomenclature updates. 
Asana Task: https://app.asana.com/0/1205827492903547/1207436785881255
> FIX: Data Dictionary Updates from Ops Analytics 

- src/lamp_py/ingestion/convert_gtfs_rt.py
This is the only thing I can find that could be causing increasing run-times on Ingestion prod.
> FIX: [Ingestion] always clean and move files

- .github/actions/run_task/action.yaml
- .github/actions/run_task/run_task.sh
- .github/workflows/run-task.yaml
- src/lamp_py/runtime_utils/env_validation.py
- src/lamp_py/tableau/hyper.py
- src/lamp_py/tableau/pipeline.py
We're now going to be publishing to tableau from staging in addition to prod. The Tableau Project is currently hardcoded to aim at the prod location. Create and use an environmental variable that stores the appropriate project for each instance of the publisher application.
Asana Task: [🚀 Stand up staging Publisher](https://app.asana.com/0/1205827492903547/1206391938568280/f)
> Feat: Add Tableau Project env var

- src/lamp_py/ingestion/glides.py
- src/lamp_py/migrations/versions/metadata_dev/002_26db393ea854_update_glides_location_column_names.py
- src/lamp_py/migrations/versions/metadata_prod/003_26db393ea854_update_glides_location_column_names.py
- src/lamp_py/migrations/versions/metadata_staging/002_26db393ea854_update_glides_location_column_names.py
In the last attempt, there was an error converting from polars back to arrow after removing duplicate data. The schema would become slightly modified, throwing errors when trying to blend it with the existing schema. Now run a cast after converting back to arrow.
> Fix Glides Migration

- src/lamp_py/publishing/index.html
> FIX: OPMI Typo

- src/lamp_py/publishing/index.html
Incorporates PRs #464 and #463 
Fixes incorrect symbols on GTFS Archive example.
> FIX: LAMP Public Webpage Updates

- .github/workflows/ci_python.yaml
- src/lamp_py/tableau/jobs/bus_performance.py
stop_arrival_dt and stop_departure_dt are currently in UTC, but Ops Analytics would like them to be in Eastern Time for all flows and dashboards
Asana Task: [<asana_ticket_url>](https://app.asana.com/0/1205827492903547/1209312681633177)
> Bus datetime conversion

- src/lamp_py/tableau/jobs/bus_performance.py
Add conversion for seconds cols as requested in ticket below:
Asana Task: [<asana_ticket_url>](https://app.asana.com/0/1189492770004753/1209312681633177)
> Add conversion for seconds after midnight cols

- Data_Dictionary.md
Update OPMI link as per Heather's request and include Ops Analytics.
> update opmi link & include Ops Analytics as well

- src/lamp_py/tableau/jobs/bus_performance.py
date conversion of 'service_date' using polars
Asana Task: [<asana_ticket_url>](https://app.asana.com/0/1189492770004753/1209312681633171)
> polars date conversion for service_date

- src/lamp_py/tableau/jobs/bus_performance.py
Handling service_date Type Issues
Asana Task: [<asana_ticket_url>](https://app.asana.com/0/1205827492903547/1209312681633171)
> FIX: service_date type in bus schema from string to date_type required

- src/lamp_py/ingestion/convert_gtfs_rt.py
- tests/ingestion/test_ingest.py
followup to the other light rail fix from earlier. need to clear out light rail from incoming bucket
> (fix) remove handler for light rail so it goes to error bucket

- runners/run_gtfs_rt_parquet_converter.py
- src/lamp_py/runtime_utils/remote_files.py
- src/lamp_py/tableau/hyper.py
- src/lamp_py/tableau/jobs/filtered_hyper.py
Various fixes
* Float types not being properly converted to hyper SqlTypes - error observed when trying to convert to hyper. 
* Output dev-green data to internal archive instead of public bucket - [Ticket](https://app.asana.com/1/15492006741476/project/1189492770004753/task/1210039594771502?focus=true)
* Fix sort order of listed files to get the right files into the "last-N-days" - logical fix
> (fix) tableau output fixes - datatypes, archive bucket, and sort order

- src/lamp_py/migrations/versions/performance_manager_staging/011_5e3066f113ff_backfill_rt_rail_2025_04_04_to_2025_04_18.py
- src/lamp_py/migrations/versions/performance_manager_staging/012_9b461d7aa53a_backfill_rt_rail_2025_04_04_to_2025_04_22.py
typo in query (date < 2024) resulted in no change in metadata table. correcting that and other typo. verified in select statement
> (fix) fix migration query for both staging and prod - bump staging uuid

- runners/run_gtfs_rt_parquet_converter.py
- runners/run_query_s3_with_date_range.py
- src/lamp_py/bus_performance_manager/event_files.py
- src/lamp_py/runtime_utils/remote_files.py
- src/lamp_py/tableau/conversions/convert_gtfs_rt_trip_updates.py
- src/lamp_py/tableau/conversions/convert_gtfs_rt_vehicle_position.py
- src/lamp_py/tableau/jobs/filtered_hyper.py
- src/lamp_py/tableau/pipeline.py
- src/lamp_py/utils/filter_bank.py
[ticket](https://app.asana.com/1/15492006741476/project/1189492770004753/task/1209347095723228?focus=true)
follow on with additional requirements from stakeholders
* add some error handling for empty datasets
* shift the rolling window to today() - 1 day to eliminate OSError contention with ingestion and perf_mgr reading the same file
* add heavyrail filters and outputs to tableau
> (feat) Add new output for prod GTFS-RT to tableau

- src/lamp_py/performance_manager/flat_file.py
- src/lamp_py/tableau/jobs/rt_rail.py
finishing backfill task for 4/22 data
verified data backfilled in databases
> (fix) following successful migration, upping versions to regenerate flat file and all_RT_fields

- analysis/check_data_all_days_in_LAMP_ALL_RT_fields.py
- analysis/prism.py
- analysis/sample_data.py
- pyproject.toml
- src/lamp_py/migrations/migration_template_generator.py
- src/lamp_py/migrations/versions/performance_manager_staging/011_5e3066f113ff_backfill_rt_rail_2025_04_04_to_2025_04_18.py
* remove impl of failed migration - add comment stating migration did not occur
* add some analysis tools - to be improved
* add migration template generator - to be improved
* add myself to authors
> (feat) various cleanup tasks and analysis tools - no deployed impact

- .env
- .env.template
- .envrc
- .gitignore
- runners/run_bus_parquet_hyper.py
- runners/run_tableau_upload.py
- src/lamp_py/tableau/hyper.py
- src/lamp_py/tableau/jobs/filtered_hyper.py
- src/lamp_py/tableau/pipeline.py
- src/lamp_py/tableau/server.py
[Asana Task](https://app.asana.com/1/15492006741476/project/1189492770004753/task/1209901858888650?focus=true)
Fixes and Features for uploading to Tableau Cloud
- (feat) add pat authentication option - allow both pat and pw
- (feat) add additional .env.lamp_private to have environment or user specific variables, ignored by gitignore so values arent committed
- (fix) correct bug discovered when no dataframe filter is applied during tableau parquet generation
> (feat) tableau authorization improvements and integration for tableau cloud

- analysis/check_bus.py
- runners/run_bus_recent_events.py
- src/lamp_py/aws/s3.py
- src/lamp_py/bus_performance_manager/event_files.py
- src/lamp_py/bus_performance_manager/pipeline.py
- src/lamp_py/bus_performance_manager/write_events.py
- src/lamp_py/tableau/jobs/bus_performance.py
- src/lamp_py/tableau/jobs/filtered_hyper.py
[Ticket](https://app.asana.com/1/15492006741476/project/1189492770004753/task/1210578092051395?focus=true)
Implement local regeneration of BUS_RECENT dataset. 
Changes to analysis scripts to look at bus data - 
Additionally apply the regeneration of the most recent 7 days of bus_vehicle_events to allow BUS_RECENT datasets to be automatically up to date when columns are added.
> (feat) local regeneration of bus_recent dataset

- src/lamp_py/tableau/conversions/convert_gtfs_rt_trip_updates.py
filter clause is a bug on lrtp task
> fix: remove stray filter clause

- src/lamp_py/bus_performance_manager/events_tm.py
- src/lamp_py/bus_performance_manager/pipeline.py
- src/lamp_py/bus_performance_manager/write_events.py
Two minor fixes:
- indentation bug to handle tm files not existing.
- try catch to ignore regenerating recent bus data when service date has not started yet (12am to 4 am est) -
> fix(bus): correct minor bugs that report errors that are low priority
