py_gtfs_rt_ingestion/ingest.py, py_gtfs_rt_ingestion/py_gtfs_rt_ingestion/__init__.py, py_gtfs_rt_ingestion/py_gtfs_rt_ingestion/config_base.py, py_gtfs_rt_ingestion/py_gtfs_rt_ingestion/config_rt_alerts.py, py_gtfs_rt_ingestion/py_gtfs_rt_ingestion/config_rt_trip.py, py_gtfs_rt_ingestion/py_gtfs_rt_ingestion/config_rt_vehicle.py, py_gtfs_rt_ingestion/py_gtfs_rt_ingestion/config_rt_vehicle_pos.py, py_gtfs_rt_ingestion/py_gtfs_rt_ingestion/configuration.py, py_gtfs_rt_ingestion/tests/test_configuration.py
Re-factor Configuration class to standard class. 
config_base.py added to hold Enumeration of ConfigType and ABC for ConfigDetail. 
- Each ConfigType should implement ConfigDetail Class in separate file for import into Configuration class.
Configuration.detail assigned to ConfigDetail ABC Class. 
Class/Methods added to Configuration class as helper to pull information for Configuration.detail ABC class:
- Configuration.config_type -> ConfigType Enum
- Configuration.export_schema -> pyarrow export schema
- Configuration.record_from_entity() -> processed parquet transformation dictionary.
=> Re factor move to lib

py_gtfs_rt_ingestion/ingest.py
Add `gz_to_pyarrow` function. Responsible for threaded conversion of gzip json to pyarrow table.
- Must return either pyarrow table or filename (on conversion failure)
Added `lambda_handler` as entry point for lambda function. Launches multiprocessing conversion is async call to `gz_to_pyarrow`.
=> Ingest multiprocess

py_gtfs_rt_ingestion/ingest.py, py_gtfs_rt_ingestion/py_gtfs_rt_ingestion/__init__.py, py_gtfs_rt_ingestion/py_gtfs_rt_ingestion/configuration.py, py_gtfs_rt_ingestion/py_gtfs_rt_ingestion/convert.py, py_gtfs_rt_ingestion/py_gtfs_rt_ingestion/error.py, py_gtfs_rt_ingestion/py_gtfs_rt_ingestion/s3_utils.py, py_gtfs_rt_ingestion/tests/test_convert.py, py_gtfs_rt_ingestion/tests/test_ingest.py
Move threading back to the ingest script. It now takes a single
conversion function, that can read from either local json dot gz files
or uri paths to files hosted on s3. The conversion function is chosen
based on the input event.
* remove s3 utility to download s3 files to a temp directory. just read
the data directly using pyarrow now.
* in convert dot py, move the json -> pa.table to its own function and
add in functions using it to read json from local files and s3.
* add Configuration.empty_table to generate the base table that will be
filled in, simplifying our concat functions.
=> Streamline conversion from s3 pipeline

py_gtfs_rt_ingestion/batch_files.py, py_gtfs_rt_ingestion/py_gtfs_rt_ingestion/batcher.py, py_gtfs_rt_ingestion/py_gtfs_rt_ingestion/error.py, py_gtfs_rt_ingestion/py_gtfs_rt_ingestion/s3_utils.py, py_gtfs_rt_ingestion/tests/test_batcher.py
The batch lambda function needs to be able to trigger the ingest lambda
for each batch that it creates. The method usesboto3, and an environment
variable that contains the ingest lambdas ARN. The actual call itself is
async and run inside of the s3_utils library. There are a handful of
logging statements and exceptions to make clear whats going on / wrong.
The batch lambda script has new flags that can be used to do a dry run
(not triggering the lambda) and printing out events as json formatted
strings.
=> Add Batch.trigger_lambda functionality

py_gtfs_rt_ingestion/ingest.py, py_gtfs_rt_ingestion/py_gtfs_rt_ingestion/__init__.py, py_gtfs_rt_ingestion/py_gtfs_rt_ingestion/convert.py, py_gtfs_rt_ingestion/py_gtfs_rt_ingestion/s3_utils.py, py_gtfs_rt_ingestion/tests/test_convert.py, py_gtfs_rt_ingestion/tests/test_s3_utils.py
Add s3 object moving to `s3_utils.py`
boto3 doesn't have direct 'move' method, so 'move' action consists of 'copy' and 'delete' calls.
Probably some more work to do here with handling of bucket names and environmental variables.
=> Add function to move s3 objects between buckets

py_gtfs_rt_ingestion/batch_files.py, py_gtfs_rt_ingestion/ingest.py, py_gtfs_rt_ingestion/py_gtfs_rt_ingestion/__init__.py, py_gtfs_rt_ingestion/py_gtfs_rt_ingestion/batcher.py, py_gtfs_rt_ingestion/py_gtfs_rt_ingestion/convert.py, py_gtfs_rt_ingestion/py_gtfs_rt_ingestion/s3_utils.py, py_gtfs_rt_ingestion/pyproject.toml, py_gtfs_rt_ingestion/tests/test_ingest.py, py_gtfs_rt_ingestion/tests/test_s3_utils.py
* Use pyarrow s3 filesystem to move things about
* `file_list_from_s3` yields (URI, filesize) tuples instead of
(filename, filesize)
* Batch class no longer contains a bucket name since always using URIs
* `write_to_dataset` has filesystem argument set to s3
* updates to tests to get this all working properly.
* add default s3_prefix set to "lamp" for initial testing to library.
its used by both the ingest and batch scripts and paired with our env
variables.  there is probably a better way to set this up, but it
should be fine for now.
=> Update URI handling to get ready for dev deploy

py_gtfs_rt_ingestion/batch_files.py, py_gtfs_rt_ingestion/py_gtfs_rt_ingestion/batcher.py
Asana Task: https://app.asana.com/0/1202413225616890/1202464608350249
- adds default batch `filesize_threshold`
- add conditional for lambda event payload size in `batcher.py`
=> Fix: Batch event parsing needs default filesize threshold

py_gtfs_rt_ingestion/py_gtfs_rt_ingestion/batcher.py
Currently we don't know when a new batch is being triggered by the event size being over the AWS 256KB limit. This change adds a log message when a batch is created by the event size being too large.
Asana Task: https://app.asana.com/0/1202535370823256/1202604738421227
=> add logging for when batcher event size is over aws limit

py_gtfs_rt_ingestion/ingest.py, py_gtfs_rt_ingestion/py_gtfs_rt_ingestion/__init__.py, py_gtfs_rt_ingestion/py_gtfs_rt_ingestion/batcher.py, py_gtfs_rt_ingestion/py_gtfs_rt_ingestion/convert_gtfs_rt.py, py_gtfs_rt_ingestion/py_gtfs_rt_ingestion/s3_utils.py, py_gtfs_rt_ingestion/pyproject.toml, py_gtfs_rt_ingestion/tests/test_batcher.py
Compress ingestion event dicts to avoid hitting payload size limit.
Move S3 files in threads instead of serially.
Asana Task: https://app.asana.com/0/1189492770004753/1202454218615559/f
=> Compress Ingestion Events

.env, Dockerfile, README.md, docker-compose.yml, performance_manager/poetry.lock, performance_manager/pyproject.toml, performance_manager/thing_to_run.py
* Create `performance_manager` directory that will contain the code that
runs on our ECS tasks and describes its dependencies. It will
eventually house tests that can be run on deployment.
* Create a `Dockerfile` to describe the image that will be deployed to
ECS. It uses python:3.9-slim as its base, pulls in performance manager
and its installs its dependencies using poetry.
* Create a `docker-compose.yml` file that will spin up a PostgresDB and
a Performance Manager Image.
* Add `thing_to_run.py` file that tests out that all of the dependencies
can be imported in the container and that the db can be connected to.
This will eventually become the main entry point to the Performance
Manager.
* Update README.md to describe how to setup test environment locally.
=> Create Performance Manager Infra

.env, docker-compose.yml, performance_manager/lib/__init__.py, performance_manager/lib/postgres_utils.py, performance_manager/lib/s3_utils.py, performance_manager/lib/static_schedule.py, performance_manager/poetry.lock, performance_manager/pyproject.toml, performance_manager/tests/test_performance_manager.py, performance_manager/thing_to_run.py
* Add SQLAlchemy dependency to manage connections and calls to DataBase
while using psycopg2 as the DBAPI layer.
* Create lib to store all the code for performance manager that will be
used by top level scripts.
* Create an engine that connects to the local db for dev testing.
* Bootstrap env variables in thing to run for faster development.
* process static schedule data from s3 parquet files using ryans biz
logic.
* Create SqlBase class that all table objects will inherit from
* Create Static Subway Headways table
=> Add sqlalchemy to performance manager

.env, py_gtfs_rt_ingestion/batch_files.py, py_gtfs_rt_ingestion/ingest.py, py_gtfs_rt_ingestion/poetry.lock, py_gtfs_rt_ingestion/py_gtfs_rt_ingestion/__init__.py, py_gtfs_rt_ingestion/py_gtfs_rt_ingestion/postgres_utils.py, py_gtfs_rt_ingestion/py_gtfs_rt_ingestion/utils.py, py_gtfs_rt_ingestion/pyproject.toml, py_gtfs_rt_ingestion/tests/test_ingest.py
The performance manager application will check metadata tables for new
parquet files that can then be converted from gtfs position data into
events data used to compute dwell times, headways, and travel times.
* Replace `parquet.write_to_dataset` call with
`pyarrow.dataset.write_dataset` call. There is a known bug with the
former that prevents the `file_visitor` call back function from being
executed properly. That function is used to keep track of what parquet
files are written and to update the metadata table appropriately.
* Add psycopg2 to dependencies and add postgres utils dot py to the
library. It contains a function to build a connection to our database
and another to insert a filepath into the metadata table.
* Add load_environment function to py_gtfs_rt_ingestion project and use …
=> Write Processed Parquet Files to Metadata Table

.github/actions/lambda_deploy/action.yaml
Lambda containers don't come with libpq (the postgres library) installed
by default. As psycopg2 is pretty much a wrapper around this c library,
it throws errors when you try to import it, and our lambda cannot run.
When packaging our zip file for deployment, use a github project that
builds the libpq library into psycopy2 instead.
=> Deploy Lambda using Psycopg2 with libpq

performance_manager/lib/__init__.py, performance_manager/lib/gtfs_static_table.py, performance_manager/lib/postgres_schema.py, performance_manager/lib/postgres_utils.py, performance_manager/lib/rt_trip_updates.py, performance_manager/lib/rt_vehicle_positions.py, performance_manager/lib/s3_utils.py, performance_manager/startup.py, performance_manager/tests/july_17_filepaths.json
Add capability to process static GTFS schedule tables needed to generate performance metrics.
Tables Loaded:
- FEED_INFO
- STOPS
- ROUTES
- STOP_TIMES
- TRIPS
- CALENDAR
Moved postgres table schema definitions into `performance_manager/lib/postgres_schema.py`
Asana Task: https://app.asana.com/0/1202784843755682/1202841571879783
=> Gtfs static load

performance_manager/lib/postgres_utils.py, py_gtfs_rt_ingestion/batch_files.py, py_gtfs_rt_ingestion/poetry.lock, py_gtfs_rt_ingestion/py_gtfs_rt_ingestion/__init__.py, py_gtfs_rt_ingestion/py_gtfs_rt_ingestion/postgres_utils.py, py_gtfs_rt_ingestion/pyproject.toml
I've been unable to figure out why psycopg is unable to connect with the AWS hosted RDS. However, SQLAlchemy is able to connect. Add SQLAlchemy as a dependency and use it to insert metadata into the RDS about new parquet files that have been created.
Asana Task: <asana_ticket_url>
=> Use SQLAlchemy instead of psycopg for writing db

performance_manager/lib/l1_full_trip_events.py, performance_manager/lib/logging_utils.py, performance_manager/lib/postgres_schema.py
update `l1_full_trip_events.py` to perform all merge logic with sql
remove use of `.in` and `.notin` and replace with join logic
Pandas merge operations do not work with byte objects being used for record hashes. This update performs that merge logic in SQL to avoid pandas issues.
Asana Task: https://app.asana.com/0/1202841571879768/1202986972911822
=> fix l1 merge logic

performance_manager/lib/postgres_schema.py, performance_manager/lib/postgres_utils.py
this commit adds functions for update_on triggers in database
sqlalchemy does not support triggers natively, trigger syntax must be passed to the database by executing sqlalchemy DDL objects
Asana Task: (https://app.asana.com/0/1202841571879768/1203007791590472)
=> Add update_on columns to database

.env, performance_manager/lib/gtfs_static_table.py, performance_manager/startup.py, performance_manager/tests/demo_events.json, py_gtfs_rt_ingestion/batch_files.py, py_gtfs_rt_ingestion/dev_test_setup.py, py_gtfs_rt_ingestion/ingest.py
We had two bucket names that were non standard before we realized there were standards. Now `ingest_bucket` has been renamed `incoming_bucket` and `export_bucket` has been renamed `springboard_bucket`.
Additionally, the entry point scripts `startup.py`, `batch_files.py` and `ingest.py` all have environment variable validation functions then ensure that all required environment variables have been set before executing.
Asana Task: https://app.asana.com/0/1189492770004753/1202862782004919/f
=> Standardize Bucket Names and Validate Env Vars

performance_manager/lib/gtfs_static_table.py, performance_manager/lib/postgres_utils.py, performance_manager/lib/rt_trip_updates.py, performance_manager/lib/rt_vehicle_positions.py, performance_manager/lib/s3_utils.py
this PR adds batching of gtfs-rt file processing in event loop
`get_unprocessed_files` in `lib/postgres_utils.py` has been modified to have an additional parameter `file_limit` this parameter will limit the number of grouped paths sent from the MetadataLog table in the RDS
grouped paths will be sorted from oldest to newest so files are processed as chronologically as possible
Asana Task: https://app.asana.com/0/1202841571879768/1203021761496493
=> add batching of rt files in event loop

performance_manager/lib/gtfs_utils.py, performance_manager/lib/l1_full_trip_events.py, performance_manager/lib/postgres_schema.py, performance_manager/lib/rt_trip_updates.py, performance_manager/lib/rt_vehicle_positions.py, performance_manager/tests/july_17_filepaths.json
to facilitate metrics implementation, event records must be matched to gtfs static data.
this PR updates the processing of VEHICLE_POSITION and TRIP_UPDATE parquet files, to add matching of records to gtfs static schedule data.
this matching is accomplished by the addition of a column to the `eventsVehiclePositions` and `eventsTripUpdates` tables. the column is a foreign key that references a unique timestamp from the `staticFeedInfo` table.
using this foreign key, event records can be matched to their relevant gtfs static data for additional database join activity.
this PR also updates event processing by grouping event records by `parent_station` from gtfs static data, instead of `stop_id` from specific event records.
Asana Task: https://app.asana.com/0/1202939398067300/1203091943545605
=> match gtfs static data to event records

performance_manager/lib/__init__.py, performance_manager/lib/gtfs_static_table.py, performance_manager/lib/l2_headways.py, performance_manager/lib/postgres_schema.py, performance_manager/startup.py
this PR adds processing of l2 headways table to performance manager
insert and update logic is accomplished through all SQL calls
steps involved:
1. pull minimum timestamp_start value for records needing headways processing
2. load headways values (with 6 hours of overlapping records) into temporary headways table
3. update existing headways from temporary table
4. insert new headwasy from temporary table
Asana Task: https://app.asana.com/0/1202939398067300/1203123341195650
=> add l2 headways processing

performance_manager/lib/l1_full_trip_events.py, performance_manager/lib/l2_dwell_travel_times.py, performance_manager/lib/l2_headways.py, py_gtfs_rt_ingestion/lib/convert_gtfs_rt.py, py_gtfs_rt_ingestion/lib/postgres_utils.py, py_gtfs_rt_ingestion/lib/s3_utils.py
Changes in this PR:
1. Rate limit ingest application.
- Rate limit is achieved by limiting the number of files pulled from `file_list_from_s3` by default this values is set at 250,000. We see at maximum ~6,000 files per hour for gtfs-rt processing. The gtfs-rt `convert` function has also been limited to produce a maximum of 10 tables per event loop. 10 * 6,000 = 60,000 which is significantly less than the 250,000 files we're pulling from s3.
2. Unlimited retry attempts on `insert_metadata`.
- `insert_metadata` can not and should not fail to insert records. Any failure can be attributed to RDS connection issues which should be able to resolved while insert attempts are made.
3. Minor logging changes to `performance_manager`
Asana Task: …
=> Rate Limit Ingestion Application 

performance_manager/lib/l0_rt_trip_updates.py, performance_manager/lib/l0_rt_vehicle_positions.py
The place we get `timestamp` from is fake for all of our seed data. So can't be trusted on table load business logic.
=> don't use timestamp

performance_manager/lib/l0_rt_trip_updates.py, performance_manager/lib/l0_rt_vehicle_positions.py, performance_manager/lib/l1_full_trip_events.py, performance_manager/startup.py, performance_manager/tests/july_17_filepaths.json, py_gtfs_rt_ingestion/lib/convert_gtfs_rt.py, py_gtfs_rt_ingestion/lib/ingest.py, py_gtfs_rt_ingestion/lib/postgres_utils.py, py_gtfs_rt_ingestion/lib/s3_utils.py
This PR contains bug fixes and performance improvements that were surfaced during initial application stress testing. Main changes include:
- Run each `Converter` as it's on Process instead of Thread
- use `ThreadPoolExecutor` for moving S3 objects
- add `ThreadPoolExecutor` to yield tables from `process_files` in `convert_gtfs_rt.py` 
- pull min/max timestamps from level 0 table loading for use in level 1 table loading
- update seed paths with new `springboard` bucket objects
Asana Task: https://app.asana.com/0/1203185331040541/1203459320510156
=> Bug & Performance Improvements 

.github/workflows/ingestion-ci.yaml, .github/workflows/performance-manager-ci.yaml, performance_manager/lib/l0_rt_trip_updates.py, performance_manager/pyproject.toml
This fixes a  bug caused by the apparent batching of the `numpy.vectorize` function. 
Very infrequently a `None` type would be passed into `explode_stop_time_update` as the `stop_time_update` parameter. 
Asana Task: https://app.asana.com/0/1203185331040541/1203495730837934
=> Bug Fix: Trip Update Loading (explode_stop_time_update)

performance_manager/lib/l0_rt_trip_updates.py, performance_manager/lib/l0_rt_vehicle_positions.py, performance_manager/lib/l1_full_trip_events.py, performance_manager/startup.py
This PR is meant to improve the performance of `pull_and_transform` for Level 1 `FullTripEvents` loading. 
For each event loop, this implementation limits records pulled from Level 0 tables to having an `updated_on` timestamp greater than the `max(updated_on)` timestamp from the Level 1 `FullTripEvents` table. 
Previously, full primary key comparisons were done between the Level 0 and Level 1 tables to determine which records required loading into the Level 1 table. 
Updates and Inserts are still completed via `hash` comparisons between the `FullTripEvents` and temporary `loadFullTripEvents` tables. 
Asana Task: https://app.asana.com/0/1203185331040541/1203480946583916
=> Fix l1 pull query

.github/workflows/ingestion-ci.yaml, .github/workflows/performance-manager-ci.yaml, .pylintrc, performance_manager/pyproject.toml, py_gtfs_rt_ingestion/pyproject.toml
Unify our pylint settings across both of our python modules by putting
them in a single rc file rather than configuring them in seperate dot
toml files. It will also better work with vs code, which has issues with
multiple pylint settings inside of one project.
Update ci yaml files that are used by github actions to use the rc file.
Asana Task: <asana_ticket_url>
=> Move pylint settings from .toml files to .pylintrc

performance_manager/lib/l0_rt_vehicle_positions.py
hotfix for RT_Vehicle_Positions failure.
verifies that `vp_move_timestamp` and `vp_stop_timsetamp` were both created from pivot table
=> check for timestamp columns

py_gtfs_rt_ingestion/ingest.py, py_gtfs_rt_ingestion/lib/__init__.py, py_gtfs_rt_ingestion/lib/config_rt_bus_vehicle.py, py_gtfs_rt_ingestion/lib/config_rt_vehicle.py, py_gtfs_rt_ingestion/lib/ecs.py
This PR fixes a bug in our `ingestion` application that resulted in `trip_id` values from GTFS-RT vehicle position files not being included in parquet files. 
This PR also adds adds ECS graceful shutdown functionality to streamline CD deployments. 
Asana Task: https://app.asana.com/0/1203655790984044/1203958635792900
Asana Task: https://app.asana.com/0/1203655790984044/1203958635792903
=> trip_id bugfix & SIGTERM graceful shutdown

performance_manager/lib/__init__.py, performance_manager/lib/l1_cte_statements.py, performance_manager/lib/l1_rt_metrics.py, performance_manager/lib/postgres_schema.py, performance_manager/lib/postgres_utils.py, performance_manager/startup.py
Working version of Trips table and Metrics table loading.
Lots of SQL business logic in this change. For both the Trips and Metrics table loading, all load and compare logic is done SQL server side. Update / Insert query cleanly pulls all records requiring update and insert into dataframe.
Additional comments are needed for SQL CTE's and identification of possible edge cases that are not currently being handled. 
Asana Task: https://app.asana.com/0/1203655790984044/1203879577067931
Asana Task: https://app.asana.com/0/1203655790984044/1203655790983994
Asana Task: https://app.asana.com/0/1203655790984044/1203655790983996
=> Business Logic for Trips and Metrics table loading

py_gtfs_rt_ingestion/ingest.py, py_gtfs_rt_ingestion/lib/ecs.py, py_gtfs_rt_ingestion/lib/ingest.py
Our use of the following functions, in combination, causes `SIGTERM` signals to be thrown and blocking of main event loop.
- signal.signal
- multiprocessing.Pool.map
- multiprocessing.Manager
Launching all `Converter` processes with `multiprocessing.Pool.map_async` resolves the issue of throwing `SIGTERM` signals and blocking the main event loop. 
Also added additional steps to `check_for_sigterm` function to shutdown rds_writer_process when `SIGTERM` signal is received from AWS. 
Asana Task: https://app.asana.com/0/1203655790984049/1204005780226888
=> Fix signal+multiprocessing bug

python_src/src/lamp_py/aws/__init__.py, python_src/src/lamp_py/aws/s3.py, python_src/src/lamp_py/performance_manager/l0_gtfs_static_table.py, python_src/src/lamp_py/startup/start_ingestion.py, python_src/tests/aws/test_s3_utils.py
After combining both python packages into one, we were left with a duplicate `file_list_from_s3` functionality that had slightly different signatures (one had a threshold while the other didn't and one returned and iter of string while the other returned a list of them. We now just have on impl that all pipelines share.
* rename `file_list_from_s3_ingestion` as `file_list_from_s3` and use that one everywhere.
* get rid of itr -> list conversions that were surrounding the other impl that returned an itr
* remove uneeded imports from the aws.__init__.py file.
Asana Task: https://app.asana.com/0/0/1204188000578028/f
=> Use one impl of file_list_from_s3

python_src/src/lamp_py/aws/s3.py
Returning directories from `file_list_from_s3` causes errors in some parts of performance_manager. 
The original version of `file_list_from_s3` had the same control logic.
=> Skip directories in S3 file_list

python_src/src/lamp_py/aws/__init__.py, python_src/src/lamp_py/ingestion/__init__.py, python_src/src/lamp_py/performance_manager/__init__.py, python_src/src/lamp_py/postgres/__init__.py, python_src/src/lamp_py/startup/__init__.py, python_src/tests/ingestion/test_configuration.py, python_src/tests/ingestion/test_gtfs_rt_converter.py, python_src/tests/ingestion/test_ingest.py, python_src/tests/ingestion/test_py_gtfs_rt_ingestion.py, python_src/tests/performance_manager/test_performance_manager.py
After migrating from multiple packages to a single package, the additional imports in our init files are going to lead us to bad practices, where we're not using the full paths on our imports from sibling directories. Clean those out and clean up imports that were not using the full paths.
=> cleanup python init files in subdirs

python_src/src/lamp_py/performance_manager/l1_rt_metrics.py
The `vehicle_event_metrics` table is missing records for the first stop of all trips. 
The first stop of a trip should never have a `travel_time` value and a WHERE clause in the `update_insert_query` select statement was specifically excluding these values, to avoid metrics with negative `travel_time` values. 
Asana Task: https://app.asana.com/0/1202087614510178/1204283360272396
=> Fix metrics - first stop of trip

.github/actions/deploy/action.yaml, .github/workflows/deploy-prod.yaml, .github/workflows/deploy-staging.yaml
We want to be able to deploy to our dev, staging, and production environments. To do so, add in two new workflows for prod and staging.
Now is also a sensible time for us to change our behavior on merges to main to run CI and update our staging environment rather than our dev one. This will leave our dev one locked until we manually deploy using the github UI.
For now, prod is also going to be deployed via manual clicks on the github UI until we figure out how we want to control versioning via tags.
Asana Task: https://app.asana.com/0/0/1204283360272394/f
=> Update github workflows for more deploy options

python_src/src/lamp_py/performance_manager/gtfs_utils.py, python_src/src/lamp_py/performance_manager/l0_gtfs_rt_events.py, python_src/src/lamp_py/performance_manager/l0_rt_trip_updates.py, python_src/src/lamp_py/performance_manager/l0_rt_vehicle_positions.py, python_src/tests/performance_manager/test_performance_manager.py
Currently, performance manager processes ALL GTFS-RT Vehicle Position and Trip Update events, loading them into the RDS. Most of these events are BUS related and can be removed from the performance manager pipeline.
This PR modifies the RDS loading pipeline to remove all BUS events for Vehicle Position and Trip Update processing.
Asana Task: https://app.asana.com/0/1189492770004753/1204339091106881
=> Remove BUS events from GTFS-RT Processing

python_src/src/lamp_py/performance_manager/l0_gtfs_static_table.py, python_src/tests/performance_manager/test_performance_manager.py
Currently, performance manager processes ALL GTFS static events, loading them into the RDS. Most of these events are BUS related and can be removed from the performance manager pipeline.
This PR modifies the RDS loading pipeline to remove all BUS events for GTFS Static processing.
Asana Task: https://app.asana.com/0/1189492770004753/1204339091106883
=> Remove BUS events from GTFS Static Processing

python_src/src/lamp_py/aws/ecs.py, python_src/src/lamp_py/postgres/postgres_utils.py
This PR adds more verbose logging to our AWS ECS sigterm handling utils. 
Also includes fix to `_rds_writer_process` logging for overwrite of `process_logger` variable name. 
Asana Task: https://app.asana.com/0/1204389777951216/1204442411295589
=> ECS Logging Fix

python_src/src/lamp_py/migrations/versions/performance_manager/98aa70293578_add_heather_honorary_view.py
This PR adds the view requested by Heather Davis of OPMI. The view provides all valid combinations of route_id's and service_id's from GTFS static files that can be joined to events and trips. 
Asana Task: https://app.asana.com/0/1204389777951216/1204410607657215
=> Add `service_id_by_date_and_route` to RDS

api/lib/api/performance_manager/static_feed_info.ex, api/lib/api/performance_manager/static_trips.ex, python_src/src/lamp_py/migrations/versions/performance_manager/43153d536c2a_feed_info_init_date_trigger.py, python_src/src/lamp_py/migrations/versions/performance_manager/7f4bbec1b669_static_trips_branch_and_trunk_route_id_.py, python_src/src/lamp_py/performance_manager/l0_gtfs_static_load.py, python_src/src/lamp_py/performance_manager/pipeline.py, python_src/src/lamp_py/postgres/postgres_schema.py, python_src/tests/performance_manager/test_performance_manager.py
Feat: Add `version_pub_date` column to `static_feed_info` table
LAMP will begin using new GTFS static schedule versions on the day they are issued. 
The `feed_version` field of all GTFS static `feed_info` tables is supposed to contain an ISO UTC timestamp representing the issued datetime of the schedule. This datetime will be extracted (with an RDS trigger function) from `feed_version`, converted to the Eastern timezone service date, and inserted as an integer of `YYYYMMDD` representing the service date the schedule version should be active. 
Feat: Add branch & trunk route id processing to the `static_trips` table
In preparation for the per-caculation of scheduled metrics, `branch_route_id` and `trunk_route_id` columns are being added to the `static_trips` table. These columns will be …
=> RDS Triggers for `version_pub_date` and Static Trips trunk/branch designations

python_src/Dockerfile
By reordering when files are copied and dependencies are installed, we can improve build times when we are making when we only modify source files and not dependencies.
=> Chore: Reorder py Dockerfile for faster buildtimes

python_src/src/lamp_py/performance_manager/gtfs_utils.py, python_src/src/lamp_py/performance_manager/l0_rt_trip_updates.py, python_src/src/lamp_py/performance_manager/l0_rt_vehicle_positions.py, python_src/tests/performance_manager/test_performance_manager.py
After discussions with OPMI, new rules to match GTFS-RT events to GTFS schedules are as follows:
Matching between a GTFS-RT events and a GTFS-static schedule version will be done on a whole `start_date` / "service_date" basis. Each distinct `start_date` / "service_date" of GTFS-RT data will be matched to only one GTFS-static version. 
When ingesting live GTFS Schedule files, the `feed_active_date` will be extracted from the ISO timestamp found in the `feed_version` field of the FEED_INFO table. This will be the first date that a GTFS-static version can be applied to GTFS-RT events. 
GTFS-RT `start_date` must be between `feed_start_date` and `feed_end_date` in FEED_INFO, `start_date` must also be less than or equal to `feed_active_date`.  The most recent schedule that meets these criteria …
=> Feat: update `add_fk_static_timestamp_column` with new match logic

.tool-versions, python_src/Dockerfile, python_src/poetry.lock, python_src/pyproject.toml
Our github action CD builds are currently failing with the following:
```
AttributeError
'HTTPResponse' object has no attribute 'strict'
at /usr/local/lib/python3.9/site-packages/cachecontrol/serialize.py:54 in dumps
50│                 ),
51│                 u"status": response.status,
52│                 u"version": response.version,
53│                 u"reason": text_type(response.reason),
→  54│                 u"strict": response.strict,
55│                 u"decode_content": response.decode_content,
56│             }
57│         }
58│ 
The command '/bin/sh -c poetry install --no-dev --no-interaction --no-ansi -v' returned a non-zero code: 1
```
Per these updates:
https://github.com/ionrock/cachecontrol/issues/292
https://github.com/python-poetry/poetry/issues/7877
This issue is …
=> Fix Github Action Build Error

docker-compose.yml
As Ryan said, its kind of like having a loaded gun sitting around since it is pointing right at our live aws buckets.
=> CHORE: Remove Ingestion from Docker Compose

python_src/src/lamp_py/migrations/versions/performance_manager/695ef31623ae_rt_trunk_id_and_route_id_processing.py, python_src/src/lamp_py/performance_manager/l1_cte_statements.py, python_src/src/lamp_py/performance_manager/l1_rt_trips.py, python_src/src/lamp_py/postgres/postgres_schema.py, python_src/src/lamp_py/postgres/postgres_utils.py
This PR updates the business logic of matching GTFS-RT trips to GTFS Static Trip ID's `static_trip_id_guess`. 
This methodology was agreed to by OPMI during QA discussions.
Exact matching is attempted between the `trip_id` recorded for the GTFS-RT trip to scheduled `trip_id`'s from the static schedule. 
Backup matching occurs by finding the scheduled trip with the closest matching parameters for the active service on the specified service date:
- `direction_id` 
- `branch_route_id` >> `trunk_route_id`
Asana Task: https://app.asana.com/0/1204517240145658/1204500786018315
Asana Task: https://app.asana.com/0/1204517240145658/1204449669814308
=> Updated GFTFS RT to Static Trip ID Matching

python_src/src/lamp_py/migrations/versions/performance_manager/014_18d962b3df59_remove_trip_fields_from_events.py, python_src/src/lamp_py/performance_manager/l0_gtfs_rt_events.py, python_src/src/lamp_py/postgres/postgres_schema.py, python_src/tests/performance_manager/test_performance_manager.py
Our `vehicle_events` table still contains columns that are duplicated in the `vehicle_trips` table. This change removes the following columns from `vehicle_events`:
- service_date
- route_id
- vehicle_id
- start_time
- direction_id
Asana Task: https://app.asana.com/0/1204614792357231/1204616772301249
=> chore: drop trips columns from `vehicle_events` table

python_src/src/lamp_py/performance_manager/l1_rt_metrics.py
OPMI has requested that all headways be calculated as departure to departure for every stop. 
Previously, the first stop of every trip was departure to departure and all other stops were calculated as arrival to arrival. 
Asana Task: https://app.asana.com/0/1204614792357231/1204659932565026
=> All Headways as Departure to Departure 

python_src/src/lamp_py/migrations/versions/performance_manager/001_be4c10c548f0_initial_rds_schema.py, python_src/src/lamp_py/migrations/versions/performance_manager/015_4fe83fd4091d_timestamp_to_static_version_key.py
Deploy to dev failed on mis-matched constraint names in AWS RDS. 
This fixes the constraint names so that migration occurs correctly. 
Asana Task: https://app.asana.com/0/1204614792357231/1204659932565030
=> Fix Constraint Names in migration 015

python_src/src/lamp_py/migrations/versions/performance_manager/017_37d97f420d54_add_prev_and_next_trip_stops.py, python_src/src/lamp_py/performance_manager/l1_rt_trips.py, python_src/src/lamp_py/postgres/postgres_schema.py, python_src/tests/performance_manager/test_performance_manager.py
Our view for OPMI RT data uses `lag` and `lead` functions to calculate prev trip_stop information on the fly. 
To increase performance, the previous and next stop for each `vehicle_event` RT record will be pre-computed and saved in the `vehicle_events` database table. 
Asana Task: https://app.asana.com/0/1204817744674813/1204881066211313
=> feat: pre-calculate prev and next trip_stop pk_id in `vehicle_events`

python_src/src/lamp_py/ingestion/ingest.py
The pool as currently written causes SIGTERMS to be thrown on child processes if a certain race condition is lost, which can happen when using the default ubuntu subprocess starting method. To fix this, add in a `pool.close` and `pool.join` call inside of the pools with block.
=> Add pool.close and pool.join statements to ingest

python_src/src/lamp_py/migrations/versions/performance_manager/017_37d97f420d54_add_prev_and_next_trip_stops.py, python_src/src/lamp_py/performance_manager/l1_rt_trips.py, python_src/src/lamp_py/postgres/postgres_schema.py, python_src/tests/performance_manager/test_performance_manager.py
Migration 37d97f420d54 has locked up the RDS for over a week. 
Since we don't know how long this migration could continue for, I believe it is prudent to just cancel the migration and implement this change on the PROD RDS during DB creation.
=> fix: skip migration 37d97f420d54

python_src/src/lamp_py/ingestion/convert_gtfs.py, python_src/src/lamp_py/ingestion/convert_gtfs_rt.py, python_src/src/lamp_py/ingestion/converter.py, python_src/src/lamp_py/ingestion/ingest.py, python_src/src/lamp_py/ingestion/pipeline.py, python_src/tests/ingestion/test_gtfs_converter.py
Functionality to verify S3 delete/move operations was previously added to ingestion because of duplicate processing errors we were seeing with GTFS files. 
These errors have since been traced back to how Delta populates our `incoming` S3 buckets with two processes running in parallel creating a race condition with file writing to S3. 
Removing the delete/move verification from ingestion because we've never gotten a log indicating that the delete/move didn't work and it adds unnecessary overhead. 
Asana Task: https://app.asana.com/0/1204921490312295/1205063998912225
=> reversion: Remove Delete Verification from Ingestion

python_src/src/lamp_py/migrations/versions/performance_manager/018_a4870e30ec68_remove_hash_columns.py, python_src/src/lamp_py/performance_manager/README.md, python_src/src/lamp_py/performance_manager/gtfs_utils.py, python_src/src/lamp_py/performance_manager/l0_gtfs_rt_events.py, python_src/src/lamp_py/performance_manager/l0_gtfs_static_mod.py, python_src/src/lamp_py/performance_manager/l0_rt_trip_updates.py, python_src/src/lamp_py/performance_manager/l0_rt_vehicle_positions.py, python_src/src/lamp_py/performance_manager/l1_cte_statements.py, python_src/src/lamp_py/performance_manager/l1_rt_metrics.py, python_src/src/lamp_py/performance_manager/l1_rt_trips.py, python_src/src/lamp_py/postgres/postgres_schema.py, python_src/src/lamp_py/postgres/seed_metadata.py, python_src/tests/performance_manager/test_performance_manager.py
This PR removes the `trip_hash` and `trip_stop_hash` columns from all tables on the RDS.
This has far reaching implications to the business logic of the entire event loading apparatus of the application. 
This PR also includes removing the `event_metrics` table and just merging it into the `vehicle_events` table to reduce join logic and duplicate data.
Asana Task: https://app.asana.com/0/1204921490312295/1204999066398940
=> feat: Remove all `hash` columns from RDS

python_src/src/lamp_py/aws/s3.py, python_src/src/lamp_py/ingestion/convert_gtfs.py, python_src/src/lamp_py/ingestion/convert_gtfs_rt.py, python_src/src/lamp_py/performance_manager/README.md, python_src/src/lamp_py/performance_manager/flat_file.py, python_src/src/lamp_py/performance_manager/pipeline.py, python_src/tests/ingestion/test_gtfs_converter.py, python_src/tests/performance_manager/test_performance_manager.py
Create method to write a flat file from the database for a given service date. It joins the Vehicle Events, Vehicle Positions, and Static Stops tables into a format third parties can use to read performance data.
Add flat file writing to performance manager event loop after new data is generated from gtfs realtime files. Write flat files for service dates from newly processed data.
Asana Task: https://app.asana.com/0/1204931901750655/1204907226653447/f
Asana Task: https://app.asana.com/0/1204931901750655/1204907226653449/f
=> Schedule flat file write 2

python_src/src/lamp_py/performance_manager/flat_file.py
A new env var is used for the s3 bucket that we'll write our public flat files to. Write the flat files iff that env ver exists.
Asana Task: https://app.asana.com/0/1204931901750660/1204907226653452/f
=> Write Flat Files to Public Archvie Bucket

python_src/src/lamp_py/migrations/versions/performance_manager_prod/sql_strings/strings_001.py, python_src/src/lamp_py/migrations/versions/performance_manager_staging/sql_strings/strings_001.py
`previous_canonical_stop_sequence` field added to OPMI RDS view based on request during touch point meeting on 13 September 2023. 
Asana Task: https://app.asana.com/0/1204931901750675/1205499565957359
=> feat: add `previous_canonical_stop_sequence` to OPMI view

python_src/src/lamp_py/ingestion/config_rt_alerts.py, python_src/src/lamp_py/ingestion/config_rt_bus_trip.py, python_src/src/lamp_py/ingestion/config_rt_bus_vehicle.py, python_src/src/lamp_py/ingestion/config_rt_trip.py, python_src/src/lamp_py/ingestion/config_rt_vehicle.py, python_src/src/lamp_py/ingestion/convert_gtfs_rt.py, python_src/src/lamp_py/ingestion/gtfs_rt_detail.py
Pre-Sorting table data, before writing to Parquet, allows Parquet compression algos to take advantage of low cardinality data. 
The following drop in file sizes has been observed:
Vehicle Positions (1 hour dataset)
63 MB → 4.9 MB
Trip Updates ( 1 hour dataset)
132MB → 26.5 MB
Asana Task: https://app.asana.com/0/1204931901750675/1205499565957353
=> feat: Pre-Sort Pyarrow Tables to write smaller Parquet files

python_src/src/lamp_py/migrations/versions/performance_manager_prod/001_5d9a7ee21ae5_initial_prod_schema.py, python_src/src/lamp_py/migrations/versions/performance_manager_prod/sql_strings/strings_001.py, python_src/src/lamp_py/migrations/versions/performance_manager_staging/001_5d9a7ee21ae5_initial_prod_schema.py, python_src/src/lamp_py/migrations/versions/performance_manager_staging/sql_strings/strings_001.py, python_src/src/lamp_py/performance_manager/README.md, python_src/src/lamp_py/performance_manager/l1_rt_trips.py, python_src/src/lamp_py/postgres/postgres_schema.py, python_src/tests/performance_manager/test_performance_manager.py
Add `sync_stop_sequence` field to performance manager based on OPMI request.
`sync_stop_sequence` is a generated stop_sequence value that is meant to be consistent across parent stations for different branch-routes on the same trunk-route.
Asana Task: https://app.asana.com/0/1205634094440864/1205670479715896
=> feat: add `sync_stop_sequence` field to performance manager

python_src/src/lamp_py/ingestion/convert_gtfs_rt.py, python_src/src/lamp_py/ingestion/pipeline.py, python_src/src/lamp_py/performance_manager/gtfs_utils.py, python_src/src/lamp_py/performance_manager/l0_rt_trip_updates.py, python_src/src/lamp_py/performance_manager/l0_rt_vehicle_positions.py, python_src/src/lamp_py/performance_manager/l1_rt_trips.py
When processing trips, we need to compute a start time for added trips. We've coded doing that based on the minimal vp move and vp stop timestamps for a given trip. However, this flow triggers a failure if there are only Trip Update records for this event. In those cases, use the minimal tu stop timestamp as well.
=> FIX: Use Trip Updates to help compute start time

.github/actions/deploy/action.yaml, .github/workflows/deploy-dev.yaml, .github/workflows/deploy-prod.yaml, .github/workflows/deploy-staging.yaml
Asana Task: <[asana_ticket_url](https://app.asana.com/0/1113179098808463/1205367032564122/f)>
This PR updates the deploy workflow to use v2 of the shared `build-push-ecr` and `deploy-ecs` actions. These updated actions assume an IAM role instead of relying on long-lasting AWS keys for an IAM user
Successful dev deployment [here](https://github.com/mbta/lamp/actions/runs/6553421551)
=> Chore: Update GitHub actions to use assumed role

.env, .github/actions/python_deps/action.yaml, .pylintrc, .tool-versions, python_src/Dockerfile, python_src/poetry.lock, python_src/pyproject.toml, python_src/src/lamp_py/aws/s3.py, python_src/src/lamp_py/performance_manager/pipeline.py, python_src/src/lamp_py/tableau/__init__.py, python_src/src/lamp_py/tableau/hyper.py, python_src/src/lamp_py/tableau/jobs/gtfs_rail.py, python_src/src/lamp_py/tableau/jobs/rt_rail.py, python_src/src/lamp_py/tableau/pipeline.py, python_src/src/lamp_py/tableau/server.py
This change updates the LAMP project to allow for the direct publishing of Tableau HyperFiles to Tableau Server. 
Tabluea HyperFiles are created from flat parquet files saved on a public S3 bucket. Each `HyperJob` contains `run_hyper` and `run_parquet` functionality.
`run_hyper` is responsible  for creating and updating Tableau HyperFiles, using the Tableau Server API, from parquet files saved on a public S3 bucket.
`run_parquet` is responsible for creating and updating parquet files saved on a public S3 bucket. 
Use of the `tableauhyperapi` and `tableauserverclient` libraries required the updating of the Python version to 3.10. This is to avoid conflicts with `botocore` library the relies on an older version of the Python `requests` library. 
Asana Task: …
=> feat: HyperFile API Publishing and Parquet Flat File Creation

python_src/src/lamp_py/tableau/pipeline.py, python_src/src/lamp_py/tableau/server.py
`tableau_server` function call being in function signature was causing Exception at import time. Move function calls out of parameter declaration. 
Also move HyperJob creation into function to avoid creation of jobs at import.
=> FIX: Tableau Server Import Exception 

python_src/src/lamp_py/performance_manager/l0_gtfs_rt_events.py, python_src/src/lamp_py/performance_manager/l0_gtfs_static_load.py, python_src/src/lamp_py/postgres/postgres_utils.py
Some of our subquery execution times have blown up and the assumption is that they will be more performative if we run `VACUUM (ANALYZE)` on static tables after a static schedule is processed.
* add a new function to run vacuum analyze on a table to the DatabaseManager class.
* use that function on static tables after new data is loaded.
* use that function on vehicle events and vehicle trips tables after processing a batch of gtfs_rt data.
=> Run vacuum analyze on static tables

python_src/src/lamp_py/tableau/jobs/rt_rail.py, python_src/src/lamp_py/tableau/pipeline.py
Fix type overload on `HyperRtRail` Job
Skip processing of `HyperStaticStopTimes` because it causes out of memory on ecs.
=> FIX: Parquet writes failing from  performance manager

python_src/src/lamp_py/performance_manager/pipeline.py
Several issues exist with writing parquet files at scale. Need to stop the writing process until better solution can be implemented.
=> temp: parquet file writing process needs revisions

python_src/src/lamp_py/performance_manager/pipeline.py, python_src/src/lamp_py/postgres/postgres_utils.py, python_src/src/lamp_py/runtime_utils/env_validation.py, python_src/src/lamp_py/tableau/hyper.py, python_src/src/lamp_py/tableau/jobs/gtfs_rail.py, python_src/src/lamp_py/tableau/jobs/rt_rail.py, python_src/src/lamp_py/tableau/pipeline.py
The current Parquet -> Tableau pipeline process is flawed in the amount of memory required to create parquet files from DB SELECT queries. This change is meant to result in a fixed amount of memory usage, no matter what the number of results are returned from a DB query, when creating a parquet file. 
This fixed memory usage is achieved by utilizing the `yield_per` method of the SQLAlchemy `Result` object, as well as the `RecordBatch` object of the pyarrow library. 
In testing, memory usage for the creation of a parquet file from the `static_stop_times` table maxes out at approximately 5-6GB. 
If memory usage needs to be further limited, the `write_to_parquet` function of `DatabaseManager` offers a `batch_size` parameter to limit the number for records flowing into a parquet file per …
=> FIX: Stream DB Results to Parquet Files

python_src/src/lamp_py/tableau/jobs/rt_rail.py
```
max_stats["service_date"]
```
statement was returning `datetime.date` object that was being piped direction into SQL statement for comparison to `vehicle_trips.service_date` which is an `Integer` field in the format of `YYYYMMDD`.
This change converts the `datetime.date` object into string representation of `YYYYMMDD` for the SQL statement comparison.
=> FIX: LAMP_ALL_RT_fields incorrect SQL comparison

.github/workflows/deploy-base.yaml
The secrets should be as they are in the the repo's secrets. Additionally, they need to be accessed via the `secrets` variable, not the `inputs` variable.
=> FIX: Update how Secrets are used in Base Deploy

python_src/pyproject.toml, python_src/src/lamp_py/tableau/hyper.py, python_src/src/lamp_py/tableau/jobs/gtfs_rail.py, python_src/src/lamp_py/tableau/jobs/rt_rail.py, python_src/src/lamp_py/tableau/pipeline.py, python_src/src/lamp_py/tableau/server.py
This change has some minor updates to our parquet file writing process that should be helpful prior to our push to the prod environment.
- decrease `batch_size` for initial parquet file creation to reduce memory usage
- clean up `LAMP_ALL_RT_fields` schema 
- add `gc.collect()` call to end of parquet file creation process
=> CHORE: Clean Up Parquet File Writing

.github/workflows/change_task_count.yaml, .github/workflows/deploy-base.yaml, .github/workflows/deploy-prod.yaml, .github/workflows/deploy-staging.yaml, .github/workflows/manual-deploy.yaml
* Inputs need to be passed in from the workflow dispatch to the base workflow as booleans, so use a fromJson function to flip them.
* Rename the env-name input to environment so that it matches with the workflow dispatch name.
* Pass the environment string, not the name of the variable.
* Add prod to list of environments we can change the task count for.
=> FIX: More bugs in Manual Deploy Workflow

python_src/poetry.lock, python_src/pyproject.toml, python_src/src/lamp_py/tableau/server.py
Updates to the Tableau `tableauserverclient` library borked our Hyper File uploading per this: https://github.com/tableau/server-client-python/issues/1299
Downgrading library to fix, will test with updated version if fix  is released.
=> FIX: Downgrade TSC Library

python_src/src/lamp_py/tableau/jobs/rt_rail.py
Add `stop_name` and `previous_stop_name` values to LAMP_ALL_RT field hyper  file extract. 
These fields are joined from `static_stops` table.
=> FEAT: Add `stop_name` and `previous_stop_name` values to LAMP_ALL_RT_fields hyper file

python_src/src/lamp_py/tableau/jobs/rt_rail.py
Fix for following feedback from Heather Davis on LAMP_ALL_RT_fields Hyper file extract: 
> In the all RT fields view, the stop arrival sec and previous stop departure sec fields are not calculated properly -- they seem to be in GMT rather than EST/EDT. Pre-11/5/23, they are 14,400 seconds or 4 hours too large, and post-11/5/23 they are 18,000 seconds or 5 hours too large. The datetime fields are in the correct time zone and do account for DST.
> The stop departure datetime field does not have an associated field in seconds after midnight (i.e. stop departure sec). Can you please add this field?
=> FIX: Update ALL_RT_fields to fix UTC timezone adjustement on seconds fields

python_src/src/lamp_py/tableau/hyper.py, python_src/src/lamp_py/tableau/server.py
When finding a Tableau datasource, based on name, datasources with the same name, in multiple projects could result in unexpected hyper file update behavior. 
`datasource_from_name` function updated to also match datasource based on expected tableau project name.
=> FIX: Check Project of Datasource Name

python_src/src/lamp_py/tableau/jobs/rt_rail.py
After consulting with the `#tid-eningeering` slack channel, this guide was provided (https://database.guide/how-at-time-zone-works-in-postgresql/) pointing me in the correct direction to make the LAMP_ALL_RT Query produced the same results no matter the SESSION timezone of the query runner. 
Instantiating a new timestamp object at a specified timezone is done with the following:
```
TIMESTAMP WITHOUT TIME ZONE AT TIME ZONE '....'
```
Creation of the `start_datetime` and `static_start_datetime` fields was also streamlined, converting `service_date` directly to a timestamp object (without a time zone) and then add seconds from `start_time` or `static_start_time` using  the postgres `make_interval` function. 
This should conclude the timestamp and time zone adventures in the LAMP_ALL_RT …
=> FIX: Remove SESSION timezone from LAMP_ALL_RT Query

python_src/src/lamp_py/migrations/versions/performance_manager_prod/003_ae6c6e4b2df5_extend_service_id_view.py, python_src/src/lamp_py/migrations/versions/performance_manager_prod/sql_strings/strings_003.py, python_src/src/lamp_py/migrations/versions/performance_manager_staging/003_ae6c6e4b2df5_extend_service_id_view.py, python_src/src/lamp_py/migrations/versions/performance_manager_staging/sql_strings/strings_003.py, python_src/src/lamp_py/performance_manager/l1_rt_trips.py, python_src/src/lamp_py/postgres/postgres_schema.py
Ops Analytics has requested a change to the `service_id_by_date_and_route` export VIEW. 
This change extends the generation of service id's (by date and route) to the `feed_end_date` of the latest available static schedule. 
Updated calculation of canonical_stop_sequence to use row_number function along with associated migration of existing data. 
Downgrade action has been excluded from this migration because the VIEW should never be reverted.
=> FIX: Update service_id_by_date_and_route VIEW

python_src/src/lamp_py/ingestion/convert_gtfs_rt.py
Ingestion is running out of memory processing very large trip update tables. 
This fix changes the way RT table data is stored during ingestion loops.
Previously, `json.gz` table data was stored as a list of individual pyarrow tables, that was concatenated before writing to parquet. 
The new method concats each `json.gz` pyarrow table to a main pyarrow table when each table is extracted.
=> FIX: Ingestion RT table save for yield

python_src/src/lamp_py/tableau/jobs/rt_rail.py
Ops Analytics reported an issue with the Tableau staging dataset, where data would be cut off at 1AM, but records existed until 2AM:
I believe this is caused by spurious early records from the next day's `service_date` cutting of parquet file updates for the previous `service_date`. 
This fix updates an additional day (looking back) of `service_date` records to avoid this issue.
=> FIX: Tableau Parquet file missing records for end of service_date

python_src/src/lamp_py/tableau/jobs/gtfs_rail.py
The service_id_by_date_and_route VIEW dataset cannot be updated in the same manner as the other GTFS Static datasets being sent to tableau.
This change allows the service_id_by_date_and_route VIEW dataset to be re-created instead of updated whenever new static schedule data is available. 
Asana Task: https://app.asana.com/0/1205827492903547/1206273298673484
=> FIX: Always Create new service_id_by_date_and_route parquet

python_src/src/lamp_py/aws/ecs.py, python_src/src/lamp_py/aws/s3.py, python_src/src/lamp_py/ingestion/convert_gtfs_rt.py, python_src/src/lamp_py/ingestion/converter.py, python_src/src/lamp_py/ingestion/ingest.py, python_src/src/lamp_py/ingestion/pipeline.py, python_src/src/lamp_py/postgres/postgres_utils.py, python_src/tests/ingestion/test_gtfs_converter.py, python_src/tests/ingestion/test_gtfs_rt_converter.py, python_src/tests/ingestion/test_ingest.py
The RDS writer process waits for items to be put on a metadata queue, pops them off, and then writes that file to the metadata. In the past, the queue was typed with any, as it was being populated with an obscure pyarrow object we couldn't deduce properly.
With the recent changes to how we write parquet files, these changed to strings. This caused the process to fail since it was attempting to pull a `path` attribute out a string, causing an uncaught exception.
I've updated the process to expect a string from the queue and put in typing hints that should prevent an error like this in the future.
Asana Task: https://app.asana.com/0/1205827492903547/1206288301107382/f
=> Fix rds writer process and with more typing

python_src/src/lamp_py/performance_manager/l0_gtfs_static_load.py, python_src/src/lamp_py/runtime_utils/infinite_wait.py
Add a new file and function `infinite_wait` in runtime utilities to pause a process without killing it, waiting for user interaction. In the static load function, pause the process if an error occurs.
Asana Task: (https://app.asana.com/0/1205827492903547/1206050538281288/f)
=> Add pause utility and use after static load failure

python_src/src/lamp_py/performance_manager/l1_rt_trips.py
Found this incorrect WHERE clause while debugging a separate issue raised by ops analytics.
=> FIX: Incorrect WHERE clause on static_version_key sync

python_src/src/lamp_py/aws/ecs.py, python_src/src/lamp_py/tableau/pipeline.py
This change adds a check to the Tableau Publisher pipeline to make sure that only one is running at a time. 
Implementation was lifted from dmap-import. 
Requires ENV VARS to be added to ECS first with devops PR: https://github.com/mbta/devops/pull/1540
Asana Task: https://app.asana.com/0/1205827492903547/1206184120740467
=> FEAT: Add parallel task checking to Tableau Publisher

python_src/poetry.lock, python_src/pyproject.toml, python_src/src/lamp_py/migrations/versions/performance_manager_dev/001_5d9a7ee21ae5_initial_prod_schema.py, python_src/src/lamp_py/migrations/versions/performance_manager_dev/002_1b53fd278b10_fix_trip_id_length.py, python_src/src/lamp_py/migrations/versions/performance_manager_dev/003_ae6c6e4b2df5_extend_service_id_view.py, python_src/src/lamp_py/migrations/versions/performance_manager_dev/004_45dedc21086e_canon_stop_seq.py, python_src/src/lamp_py/migrations/versions/performance_manager_prod/001_5d9a7ee21ae5_initial_prod_schema.py, python_src/src/lamp_py/migrations/versions/performance_manager_staging/001_5d9a7ee21ae5_initial_prod_schema.py, python_src/src/lamp_py/migrations/versions/performance_manager_staging/002_1b53fd278b10_fix_trip_id_length.py, python_src/src/lamp_py/migrations/versions/performance_manager_staging/003_ae6c6e4b2df5_extend_service_id_view.py, python_src/src/lamp_py/migrations/versions/performance_manager_staging/004_45dedc21086e_canon_stop_seq.py, python_src/src/lamp_py/performance_manager/gtfs_utils.py, python_src/src/lamp_py/tableau/__init__.py
Bumping Black version to 24.1.1 required a few formatting updates. Mostly white-space changes. 
Asana Task: https://app.asana.com/0/1205827492903547/1204354793482788
=> chore: Bump Black version to 24.1.1 with file updates

python_src/src/lamp_py/aws/s3.py, python_src/src/lamp_py/performance_manager/l0_gtfs_rt_events.py, python_src/src/lamp_py/performance_manager/pipeline.py, python_src/src/lamp_py/tableau/__init__.py, python_src/src/lamp_py/tableau/pipeline.py
Deleting all remote parquet paths at application start will allow the parquet files to pick up any changes to made writing the files by the application. All files will be re-generated by the end of the first app `event_loop`. 
Asana Task: https://app.asana.com/0/1205827492903547/1206643238763144
=> FIX - Clean Remote Parquet Paths at Application Start

python_src/src/lamp_py/tableau/jobs/rt_rail.py, python_src/src/lamp_py/tableau/pipeline.py
Our performance_manager application on staging is dying, possibly because of high memory usage.
This should reduce memory usage in an attempt to avoid ECS death.
=> HOTFIX: Staging performance_manager ecs instance dying

python_src/src/lamp_py/performance_manager/l1_rt_trips.py, python_src/src/lamp_py/performance_manager/pipeline.py, python_src/src/lamp_py/postgres/postgres_utils.py, python_src/src/lamp_py/tableau/jobs/gtfs_rail.py, python_src/src/lamp_py/tableau/jobs/rt_rail.py, python_src/src/lamp_py/tableau/pipeline.py
The LAMP staging environment has been displaying excessively high memory usage and crashes during the creation of parquet files for Tableau publishing. The issue was traced back to the `write_to_parquet` function of our DatabaseManager object. 
SQLAlchemy result streaming through use of the `yield_per` method, was not behaving as intended. Instead of incrementally streaming results from a query, it was materializing the entire result stream in memory before iterating through the results. Updating the `write_to_parquet` function to use the `execute_options` parameter has resolved this issue and results are now correctly streamed incrementally and memory usage during streaming is contained to a single `batch_size` amount. 
Additionally, this change adds helper functions to our …
=> FIX: Reduce resource usage during parquet file creation

python_src/poetry.lock, python_src/pyproject.toml, python_src/src/lamp_py/tableau/jobs/rt_rail.py
Currently, the `LAMP_ALL_RT_fields.parquet` file is uploaded to S3 on every event loop. 
The change adds a check between the records >= `max_start_date` in the database and in the existing `LAMP_ALL_RT_fields.parquet` file. If the counts are equivalent, the parquet file is not re-uploaded to S3.
Also includes all dependabot updates for the week.
=> FEAT: Skip upload of LAMP_ALL_RT_fields.parquet file when no new records

python_src/src/lamp_py/aws/s3.py, python_src/src/lamp_py/performance_manager/pipeline.py, python_src/src/lamp_py/tableau/hyper.py, python_src/src/lamp_py/tableau/jobs/gtfs_rail.py, python_src/src/lamp_py/tableau/jobs/rt_rail.py, python_src/src/lamp_py/tableau/pipeline.py
Previously, all Tableau parquet files were being deleted and re-created on every application deployment.
This change utilizes the S3 `Metadata` head field to store a `lamp_version` value to determine when datasets should be re-freshed / re-created. 
Asana Task: https://app.asana.com/0/1189492770004753/1206729585163530
=> FEAT: Update Tableau Parquet files based on S3 Metdata Version field

python_src/src/lamp_py/aws/s3.py, python_src/src/lamp_py/publishing/performancedata.py
Our index.html page for performancedata.mbta.com is not being served by CloudFront because the S3 `ContentType` parameter is set to `binary/octet-stream` causing the file to be offered as a download. 
This change will upload index.html with `text/html` set for `ContentType` which should hopefully serve the file as a normal webpage. 
Asana Task: https://app.asana.com/0/1205827492903547/1204907226653450
=> FIX: Add ContentType to index.html upload

python_src/src/lamp_py/aws/s3.py
Logger is attempting to unpack None Type. Check that extra_args is dictionary before adding to logger.
=> FIX: check extra_args is dictionary

python_src/src/lamp_py/aws/s3.py, python_src/src/lamp_py/performance_manager/flat_file.py, python_src/tests/performance_manager/test_performance_manager.py
The `index.csv` file generated for On Time Performance flat files contained s3:// paths instead of https:// paths. 
This change replaces s3://bucket-name paths with https://performancedata.mbta.com.
This change also updates the `file_list_from_s3_with_details` function with more description return dictionary labels of `s3_obj_path` and `size_bytes`.
=> FIX: remove s3:// from flat file paths

src/lamp_py/migrations/versions/performance_manager_staging/006_e20a4f3f8c03_fix_null_vehicle_consist.py, src/lamp_py/performance_manager/flat_file.py, src/lamp_py/performance_manager/l0_rt_vehicle_positions.py, src/lamp_py/tableau/jobs/rt_rail.py
The vehicle consist field was recently deprecated by transit tech and an alternate data source is needed for that information to be sent to the OPMI Tableau server.
vehicle consist data will be pulled from the multi_carriage_details field and coalesced with the vehicle consist field to allow for processing periods when multi_carriage_details was not available. 
Asana Task: https://app.asana.com/0/1204931788263585/1206785855851419
=> FIX: Lost vehicle consist field in GTFS-RT VehiclePositions feed

Data_Dictionary.md, src/lamp_py/ingestion/README.md, src/lamp_py/performance_manager/README.md, src/lamp_py/publishing/index.html
This update creates a new `Data_Dictionary.md` README file for all public datasets being published by LAMP. 
This documentation will be linked via https://performancedata.mbta.com/ for public users to reference. 
Asana Task: https://app.asana.com/0/1205827492903547/1206416077842542
=> FEAT: Update README documentation for public data exports

.gitignore, pyproject.toml
Add a new dependency group to pyproject.toml that contains libraries that are useful for data investigations. I've used this flow while working on the bus stop crossing investigation and it allows me to install libraries that aren't needed by LAMP applications locally while still using LAMP utilities.
The can be installed with
`poetry install --with investigation`
I also added a directory to .gitignore where I've been putting notebook and datafiles.
=> Add Investigation Group to Dependencies

pyproject.toml, src/lamp_py/performance_manager/l1_rt_trips.py
This will hopefully fix a lot of the performance issues we are seeing in the `l1_rt_trips.py` file.
Two main changes:
1. 
Don't update trunk_route_id and branch_route_id with database functions, instead `update_branch_trunk_route_id` function will perform this operation locally, and then update the `vehicle_trips` table.
2.
perform updates in `update_stop_sequence` function on unique `service_date` and `static_version_key` combinations with for loop. Previous implementation used a where statement that compared to an array of values, that I think was not allowing our indexes to be used.
=> FIX: performance of l1_rt_trips.py updates

src/lamp_py/migrations/versions/metadata_prod/002_cce8dfee767a_re_run_input_files_from_2024_04_03.py
Execute migration on PROD metadata_log table to re-process parquet files from morning of April 3, 2024.
=> FIX: prod metdata migration to re-process failed parquet files

src/lamp_py/runtime_utils/process_logger.py, src/lamp_py/tableau/jobs/gtfs_rail.py, src/lamp_py/tableau/jobs/rt_rail.py
Very large parquet input files on PROD were resulting in ECS crashes from excessive memory usage.
After local testing, excessive memory usage was re-produced and `batch_size` values were dialed in to limit memory usage during parquet file writing operations. 
Also added some basic system profiling to logging statements `free_disk_mb` & `free_mem_pct` will hopefully help troubleshoot these types of issues more quickly in the future.
=> FIX: Parquet writing batch_size and profile logging

src/lamp_py/tableau/jobs/rt_rail.py
The query that creates the LAMP_ALL_RT OPMI dataset contains a  `canonical_stop_sequence > 1` WHERE constraint to filter out origination terminal stops from the dataset. As a side effect, this constraint also removed any trips that did not have a valid canonical_stop_sequence from the dataset. This frequently occurred on the red-line during diversions where a `branch_route_id` could not be assigned to the trip because the trip did not pass through a branch station (south of JFK/UMass). 
Ops Analytics has requested that this constraint be updated to include `OR ve.canonical_stop_sequence IS NULL` to add back the Red-line (and any other route) trips without a valid `canonical_stop_sequence`.
Merging this change will trigger a refresh of the LAMP_ALL_RT parquet file on the PROD, which will …
=> FIX: LAMP_ALL_RT dataset missing partial RED Line trips

src/lamp_py/performance_manager/flat_file.py, src/lamp_py/tableau/jobs/rt_rail.py
This change removes commuter rain data from flat file and OPMI ALL_RT export files. 
As tested on STAGING, these changes have no significant impact on query duration. 
flat file query remained constant at ~4 seconds, for one service_date
ALL_RT query stayed at ~12 seconds, for one service_date
Deployment of this change to PROD will result in re-creation of export datasets, which should be done at the end of the business day to avoid interference with Tableau dashboarding operations. 
Asana Task: https://app.asana.com/0/1205827492903547/1207059327607966
=> FEAT: Remove Commuter Rail data from exports

poetry.lock, pyproject.toml, src/lamp_py/ingestion/compress_gtfs/__init__.py, src/lamp_py/ingestion/compress_gtfs/gtfs_schema_map.py, src/lamp_py/ingestion/compress_gtfs/gtfs_to_parquet.py, src/lamp_py/ingestion/compress_gtfs/schedule_details.py, tests/ingestion/test_gtfs_compress.py
This change provides all of the scaffolding required to create compressed parquet files from GTFS Static schedules.
GTFS feed information is pulled directly from https://cdn.mbta.com/archive/archived_feeds.txt
This change is currently missing the S3 bucket sync features, since that deployment of this feature is still waiting on the Transit Data team to fix malformed schedule archives. The location of S3 operations is defined by comments.
To run locally, call:
```
from lamp_py.ingestion.compress_gtfs.gtfs_to_parquet import gtfs_to_parquet
gtfs_to_parquet()
```
and compressed schedules archives will be created in the `/tmp/compress-gtfs` folder.
Compression Performance:
For 2023, the MBTA published 108 schedules at a total size of ~1528 MB. The total size of the 2023 compressed parquet …
=> FEAT: Compress GTFS Static schedules into Yearly partitioned parquet files

src/lamp_py/migrations/versions/performance_manager_dev/006_2dfbde5ec151_sync_stop_trunk.py, src/lamp_py/migrations/versions/performance_manager_prod/003_2dfbde5ec151_sync_stop_trunk.py, src/lamp_py/migrations/versions/performance_manager_staging/007_2dfbde5ec151_sync_stop_trunk.py, src/lamp_py/performance_manager/l1_rt_trips.py
The sync_stop_sequence value should be updated by trunk_route_id, since it is agnostic to whichever branch_route_id the trip is associated with. 
This change updates the sync_stop_sequence query to update based on trunk_route_id and includes migration files for all environments to update old sync_stop_sequence values.
This issue was originally raised by Heather from ops analytics.
=> FIX: update sync_stop_sequence by trunk_route_id

.github/workflows/change_task_count.yaml
Add `bus-performance-manager` to change_task_count github action.
=> FEAT: Use Github Action to change instance count for BUS-PM application

src/lamp_py/ingestion/convert_gtfs_rt.py, src/lamp_py/ingestion/ingest.py, src/lamp_py/postgres/postgres_utils.py, tests/ingestion/test_gtfs_rt_converter.py
This change updates the ingestion app to continuously update GTFS-RT parquet files.
Continuous updates are performed on parquet files saved locally, that are then synced with the expected S3 bucket. 
No more than 2 local parquet files, for each GTFS-RT type, are ever saved locally. 
The Metadata database is updated, with processed flags being reset, whenever an update is made to a parquet file. 
Asana Task: https://app.asana.com/0/1205827492903547/1207039261301265
=> FEAT: Ingest GTFS-RT files continously

.github/workflows/deploy-base.yaml, .github/workflows/deploy-prod.yaml, .github/workflows/deploy-staging.yaml, .github/workflows/manual-deploy.yaml
TransitMaster Ingestion is a new application that will run a cron schedule on the ITD Transit Gateway subnet in staging and prod environments.
Expand the `deploy-base.yaml` to deploy this application conditionally. Set that flag to true for both prod and staging deployment scripts and add it as an input in the manual deployment script.
Asana Task: [🚌 Create ECS infrastructure TM Ingestion runs on](https://app.asana.com/0/1189492770004753/1207188685726595/f)
=> FEAT: Add workflows for deploying TM Ingestion

src/lamp_py/aws/s3.py, src/lamp_py/performance_manager/l0_gtfs_static_load.py, src/lamp_py/performance_manager/l0_rt_trip_updates.py, src/lamp_py/performance_manager/l0_rt_vehicle_positions.py, tests/conftest.py, tests/performance_manager/test_performance_manager.py
Continuous ingestion is resulting additional thrashing of RT springboard files for performance manager. This change incorporates retry logic into RT_VEHICLE_POSITION and RT_TRIP_UPDATE file loads. 
Also made a few changes to the way we read parquet datasets based on information learned since these functions were created.
=> FEAT: Retry failed parquet RT file loads

.github/workflows/deploy-base.yaml
The `mbta/actions/deploy-ecs@v2` action has been updated to have `allow-zero-desired` as an input. (https://github.com/mbta/actions/blob/main/deploy-ecs/action.yml)
This updates our deploy-base action to not fail if no instance tasks are currently running for a service.
=> FEAT: USE allow-zero-desired from deploy-ecs@v2

Data_Dictionary.md, src/lamp_py/publishing/index.html
Based on request from ops analytics.
=> feat: Remove "on-time" nomenclature from documentation 

src/lamp_py/performance_manager/l0_gtfs_static_load.py
Continuous ingestion is causing 2 parquet files to be placed into a single static file partition on our springboard bucket. 
The static table loading process should never be loading more than 1 file from a folder. 
This is a stop-gap.
=> FIX: Only pull 1 static parquet file from folder

src/lamp_py/performance_manager/alerts.py, src/lamp_py/tableau/jobs/rt_alerts.py, src/lamp_py/tableau/pipeline.py
The alerts data needs to be on tableau to allow for dashboard creation and some downstream analysis from teams unable to process parquet files.
* Add a Hyper Job for Alerts to handle the publishing
* Pull out static info from `AlertsParquetHandler` into `AlertsS3Info` and use that in both the handler and hyper job classes.
* Update tableau.pipeline.py to use different lists for running the hyper jobs and running the parquet updates.
Asana Task: [📣 Publish alerts data to Tableau](https://app.asana.com/0/1205827492903547/1207101442990597/f)
=> FEAT: Add Tableau Publishing for Alerts Data

Data_Dictionary.md, src/lamp_py/publishing/index.html
Now that Alerts data is being published to the public bucket for consumption, we need to update our public index to include its url and the data dictionary to describe its contents.
=> FEAT Update Data Dictionary for Alerts Data

src/lamp_py/performance_manager/alerts.py
Not having this was causing the alerts hyper job to fail.
=> FIX: Add "s3://" prefix to Alerts S3 path string

src/lamp_py/tableau/hyper.py
The Alerts dataset has timestamp types with timezone information in them. Add a conversion in the `convert_parquet_dtype` method that will correctly convert these pyarrow types into hyper types.
=> FIX: Add SqlType.timestamp_tz for pq -> hyper type

src/lamp_py/ingestion/convert_gtfs.py, tests/ingestion/test_gtfs_converter.py
Our previous implementation of determining a `version_key` was based on the file modified datetime of the `feed_info.txt` file in a GTFS zip archive. This method does not work for ingesting GTFS schedule information from the archive feed. 
GTFS Schedules in the archive feed have their feed_info.txt files modified during the creation of the next GTFS schedule, to update the `feed_end_date` field. Because of this, we will base the `version_key` on the `published_dt` that is extracted from the `feed_version` text of the `feed_info.txt` file.
=> FIX: GTFS Ingestion version_key based on published_dt

src/lamp_py/performance_manager/alerts.py
When an alerts dataset was being filtered with Fields that compared int64 column values against python float values, these columns were cast as float32 values, which resulted in overflow errors on timestamp fields that need the wider band of values. Convert the compare values to ints before using them to filter the dataset.
Some details on the issue can be found here:
https://github.com/apache/arrow/issues/36719
=> FIX dataset.to_table casting ints as floats

src/lamp_py/aws/s3.py
There appears to have been a change in how pyarrow dataset's read file paths with hive partitioning values. 
static table ingestion has been failing because partition columns are no longer being added to final dataframes coming out of the `read_parquet` function.
=> FIX: read_parquet dataset reading not adding hive partition columns

src/lamp_py/tableau/hyper.py
I added this type when the alerts data had timezoned datetime fields. In talking to Heather about downstream user preferences, we decided to drop the timezone part of the datetimes and ensure they were formatted to Boston time.
This type was still being used when converting the types however, causing the alerts hyper job to fail on a mismatched type. Dropping it as its no longer needed and was causing issues.
=> FIX: remove timestamp tz type from hyper type map

src/lamp_py/performance_manager/alerts.py
Initially, the processed alerts archive was partitioned into row groups via the 'last_modified_timestamp' key. After hearing back from Transit Matters, change this key to the 'active_period.start_timestamp', which should improve the types of queries they run.
=> UPDATE: Change partition key in alerts data

.github/workflows/deploy-base.yaml, Dockerfile, src/lamp_py/__version__.py, src/lamp_py/runtime_utils/env_validation.py
Add a `__version__.py`file to the lamp_py module. This file is left with a default value for local development. In our Dockerfile, overwrite this file with a passed in version argument, allowing the version to be set inside of the docker image. Update the deploy base github action to generate a unique version value for each deployment based on the latest version tag and current commit hash. Lastly, log the version when validating the environment.
Asana Task: [🛠️ Establish Version Logging & Versioning strategy](https://app.asana.com/0/1205827492903547/1206729585163530/f)
=> Add Versioning to Docker Images

src/lamp_py/aws/s3.py, src/lamp_py/ingestion/convert_gtfs_rt.py, tests/ingestion/test_gtfs_rt_converter.py
Change GTFS-RT ingestion partition from hourly to daily.
This run successfully on DEV for several days with acceptable loop duration.
TRIP_UPDATES are the limiting events for this processing. There are some potential options for optimization, if needed based on future application performance. 
Asana Task: https://app.asana.com/0/1205827492903547/1207039261301268
=> FEAT: GTFS-RT Daily Ingest

src/lamp_py/ingestion/convert_gtfs_rt.py
I goofed and removed the send_metadata call for gtfs-rt ingestion
=> FIX: Ingestion use send_metadata

Data_Dictionary.md
When Data Dictionary for Alerts dataset was originally created, MBTA GTFS-RT Enhanced docs had not been updated with Alerts fields. Now that those field docs are available, Data Dictionary is being updated to link to those enhanced field definitions. 
Asana Task: https://app.asana.com/0/1205827492903547/1207294690115490
=> FEAT: Update Alerts Data Dictionary with new GTFS-RT Enhanced field docs

src/lamp_py/ingestion/compress_gtfs/gtfs_to_parquet.py, src/lamp_py/ingestion/compress_gtfs/pipe.py, src/lamp_py/ingestion/compress_gtfs/pq_to_sqlite.py, src/lamp_py/ingestion/compress_gtfs/schedule_details.py, src/lamp_py/ingestion/ingest_gtfs.py, src/lamp_py/ingestion/pipeline.py, src/lamp_py/ingestion/utils.py, tests/ingestion/test_gtfs_compress.py
This change adds the ability to export compressed GTFS schedule data to an SQLITE db file. 
For each year partition folder, in the compressed gtfs archives, one SQLITE db file will be produced that contains a table for each GTFS schedule file that has been compressed.
This implementation utilizes the python built-in sqlite3 library. Locally, I am able to produce each SQLITE db file in about 2 minutes. 
This change also has all of the S3 sync and upload logic to fully implement the compressed GTFS process. 
Asana Task: https://app.asana.com/0/1205827492903547/1207450430015372
=> FEAT: Export compressed GTFS schedule to SQLITE db

.github/workflows/run-task.yaml
Our Tableau Publisher and TM Ingestion tasks run on ECS at scheduled times. Developers don't have permission to trigger them directly, but our GHA user does. Create a workflow to trigger these tasks, allowing us to test them outside of their scheduled times.
=> FEAT: Add a workflow to trigger ECS Tasks

src/lamp_py/mssql/mssql_utils.py
TM Ingestion `write_to_parquet` operations have been failing with the following error:
```
pyodbc.Error: ('40001', '[40001] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Transaction (Process ID 63) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction. (1205) (SQLFetch)')
```
This change adds retry logic to the `write_to_parquet` method of the `MSSQLManager` class in an effort to avoid the failure of these TM Ingestion table export jobs. 
Asana Task: https://app.asana.com/0/1205827492903547/1207692276182265
=> FIX: Retry logic for `write_to_parquet` method of `MSSQLManager`

src/lamp_py/aws/s3.py, src/lamp_py/bus_performance_manager/vehicle_events.py, src/lamp_py/runtime_utils/remote_files.py
Add Function to Choose Files for BPM Ingestion 
Instead of using the metadata db, we plan on using last modified
timestamps on incoming buckets and comparing them with the last modified
timestamps on our outgoing vehicle event files.
* Create two new S3 Utilities
* one gets the last modified file object in an s3 bucket / prefix.
* one gets all of the files in a s3 bucket / prefix that have been
modified after a given time.
* Create `remote_files.py` which will house the s3 location information
for various files LAMP uses.
* Create `bus_performance_manager/vehicle_events.py` and create the
function for collecting files that have been modified since the last
update and a function that will group those files based on service
date.
Asana Task: [🚌 Create function for choosing files for …
=> Add Function to Choose Files for BPM Ingestion

src/lamp_py/tableau/hyper.py
Ops Analytics has requested that Tableau datasets have different names based on development environment (prod, staging, dev).
This change renames staging and dev environment datasets to append `_staging` or `_dev`. Production datasets names remain un-changed. 
Asana Task: https://app.asana.com/0/1205827492903547/1207800774457790
=> FIX: name tableau dataset based on deploy environment

src/lamp_py/ingestion_tm/ingest.py, src/lamp_py/ingestion_tm/jobs/parition_table.py, src/lamp_py/ingestion_tm/jobs/whole_table.py, src/lamp_py/ingestion_tm/tm_export.py, src/lamp_py/mssql/mssql_utils.py, src/lamp_py/runtime_utils/remote_files.py, tests/ingestion_tm/test_ingest.py
* Add Block, Operator, Run and WorkPiece to the whole table ingestion jobs.
* Create new abstract base class `TMDailyTable` that will pull in daily tables from transit master. (Its largely an abstraction based on the existing `TMDailyLogStopCrossing` class.
* Add Daily Work Piece and Schedule Adherence Waiver tables to the daily log jobs.
* All TM Ingestion jobs now use Remote File Location constants to define s3 locations.
* Add tests to ensure all TM Ingestion Jobs are run in the pipeline.
Asana Task: [🚌 Ingest TM data for block, run, & operator](https://app.asana.com/0/1205827492903547/1207935724478899/f)
=> Ingest More Transit Master Tables

poetry.lock, pyproject.toml, src/lamp_py/bus_performance_manager/gtfs.py, src/lamp_py/bus_performance_manager/gtfs_utils.py, src/lamp_py/bus_performance_manager/vehicle_events.py, src/lamp_py/ingestion/compress_gtfs/gtfs_to_parquet.py, src/lamp_py/ingestion/compress_gtfs/schedule_details.py, src/lamp_py/ingestion/convert_gtfs.py, src/lamp_py/ingestion/convert_gtfs_rt.py, src/lamp_py/ingestion/glides.py, src/lamp_py/ingestion/ingest_gtfs.py, src/lamp_py/ingestion/utils.py, src/lamp_py/ingestion_tm/jobs/parition_table.py, src/lamp_py/ingestion_tm/jobs/whole_table.py, src/lamp_py/performance_manager/alerts.py, src/lamp_py/performance_manager/flat_file.py, src/lamp_py/performance_manager/l0_gtfs_static_load.py, src/lamp_py/publishing/performancedata.py, src/lamp_py/runtime_utils/remote_files.py, src/lamp_py/tableau/jobs/gtfs_rail.py, src/lamp_py/tableau/jobs/rt_rail.py, tests/bus_performance_manager/test_gtfs.py, tests/bus_performance_manager/test_gtfs_rt_ingestion.py, tests/conftest.py, tests/ingestion/test_gtfs_converter.py, tests/test_resources.py
This changes attempts to consolidate references to S3 paths all in one location. 
Original version of `remote_files.py` was modified to reduce the verbosity of calling resources defined by the file. Also added all bucket references and lamp file prefix constants to the file. 
Hopefully I found all the places where we reference S3 file locations....
Asana Task: https://app.asana.com/0/1205827492903547/1207771349226027
=> FEAT: S3 remote file paths in one location

src/lamp_py/ingestion/compress_gtfs/gtfs_to_parquet.py
PR #423 re-factor broke compressed GTFS process by prefixing the `gtfs_temp_folder` declaration with s3://. 
This change fixes that oversight.
=> FIX: Bad Compress GTFS Local Folder

.github/actions/run_task/action.yaml, .github/actions/run_task/run_task.sh, .github/workflows/ad_hoc_deploy_run.yml, .github/workflows/deploy-base.yaml, .github/workflows/run-task.yaml
This change allows LAMP Ad-Hoc ECS Task to be triggered with github action.
Ad-Hoc ECS Task created by devops PR: https://github.com/mbta/devops/pull/2184
Asana Task: https://app.asana.com/0/1205827492903547/1207556073650893
=> FEAT: Start LAMP Ad-Hoc Task with Github

src/lamp_py/ingestion/compress_gtfs/gtfs_to_parquet.py
This change fixes recent STAGING splunk failure alerts: https://mbta.slack.com/files/USLACKBOT/F07PJK23963/splunk_alert__lamp_staging_ingestion_failure
The S3 sync operation for GTFS compressed parquet files was calling the `GTFSArchive.parquet_path` method to create object upload paths. This method automatically appends `.parquet` to any file passed to it. However the `GTFS_ARCHIVE.db.gz` file is not supposed to have a `.parquet` appended. 
This change stops using the `GTFSArchive.parquet_path` method and falls back to a simple path join to create the S3 object upload path. The matches the behavior of the current PROD environment which has not seen these errors.
=> FIX: GTFS Compressed Schedule Upload

.github/actions/run_task/action.yaml, .github/workflows/ad_hoc_deploy_run.yml, src/lamp_py/ad_hoc/runner_001.py, src/lamp_py/ingestion/convert_gtfs_rt.py
This change creates and Ad-Hoc Runner script that will add a "vehicle.trip.revenue" column to RT_VEHICLE_POSITION springboard parquet files starting from December 20th, 2023. 
The Ad-Hoc runner will re-read GTFS-RT VehiclePosition input file, from the archive bucket, and produce new daily partitioned parquet files that include a "vehicle.trip.revenue" column. Existing parquet files that do not have a "vehicle.trip.revenue" column will be overwritten.
After the files have been created they are added to our metadata RDS table so that the performance manger application may re-ingest the files and add an accurate "revenue" values to the vehicle_event_trips table of the performance manger RDS. 
This process will run in parallel with LAMP's real-time performance pipeline so that customer data …
=> FEAT: Ad-Hoc Runner Script to add revenue to Springboard file

src/lamp_py/bus_performance_manager/pipeline.py, src/lamp_py/runtime_utils/remote_files.py, src/lamp_py/tableau/hyper.py, src/lamp_py/tableau/jobs/bus_performance.py, src/lamp_py/tableau/pipeline.py
This PR is currently sitting on top of https://github.com/mbta/lamp/pull/451
I can re-base once #451 is merged into main.
This change reads daily bus_event files from the public S3 bucket, concatenates them together and sends them to Tableau to be used by OPMI. This process happens in two steps:
1. Join daily bus event files together and saved joined parquet file to `tableau` partition of public bucket.
2. Tableau publisher app picks up `tableau` partition files from public bucket, converts them to a .hyper file and uploads them to ITD Tableau sever.
Two datasets are created by this process an `ALL` dataset, consisting of all available bus event files. Along with a `RECENT` dataset containing only the last 7 days of bus event files. The `RECENT` dataset will be updated on tableau …
=> FEAT: Publish BUS Performance files to Tableau

src/lamp_py/ingestion/glides.py
Ingest new `tripId` field from Glides kinesis stream. This field is flattened into it's own column, so merging with existing datasets should cause no issues. 
Asana Task: https://app.asana.com/0/1205827492903547/1208481082941326
=> FEAT: Add tripID field to glides trip_updates ingestion

src/lamp_py/ingestion/convert_gtfs_rt.py
The RT_ALERTS dataset that we ingest produces parquet files that contain columns consisting of struct types. If the struct type of the column changes, a newly ingested dataset can not be merged with the existing dataset from S3. 
If this situation emerges, the S3 dataset will be over-written by the newly ingested dataset, avoiding the merge errors for the day. This will only be applied to Alerts datasets, as the contents of Alerts RT data does not change often throughout the day. Since Alerts events are persisted with started/complete/modified timestamp fields.
=> FIX: Reset RT_ALERTS Ingestion dataset on schema change

src/lamp_py/tableau/hyper.py
Bus Performance Event parquet files utilize a new parquet type `unit32` that was not properly being converted to it's hyper file type equivalent. This change adds the correct type mapping.
=> FIX: Add parquet uint32 type to hyper file type mapping

src/lamp_py/performance_manager/flat_file.py, src/lamp_py/tableau/jobs/rt_rail.py
This change bumps the datasets versions for "subway-on-time-performance-v1" and "LAMP_ALL_RT_fields" so they will incorporate the historical revenue data that has been backfilled by our ad-hoc task. 
These changes will force a re-generation of these datasets, so they should wait to be deployed at the end of a business day. 
Asana Task: https://app.asana.com/0/1205827492903547/1208510809443305
=> FIX: Bump dataset versions to load back-filled revenue data

src/lamp_py/ingestion/glides.py
Glides began publishing a new data feed type on the evening of Dec 12, 2024. https://mbta.github.io/schemas/events/glides/com.mbta.ctd.glides.vehicle_trip_assignment.v1
This change adds a `GlidesConverter` to begin ingesting the "Vehicle Trip Assignment" feed.
Asana Task: https://app.asana.com/0/1205827492903547/1208962016232571
=> FEAT: Ingest Glides Vehicle Trip Assignment Feed

src/lamp_py/performance_manager/l0_gtfs_rt_events.py
Staging environment is showing errors because of an sql ERROR:
```nextval: reached maximum value of sequence "temp_event_compare_pk_id_seq" (2147483647)```
This change restarts the identity on the TempEventCompare table to avoid a "maximum value of sequence" error.
=> FIX: TempEventCompare max primary key error

src/lamp_py/ingestion/compress_gtfs/schedule_details.py
I believe we ran into an edge case because for the GTFS Compression process because a new schedule was issued on new years eve.
This change creates a local year folder for 1 extra year in the future to resolve this issue.
=> FIX: Compressed GTFS Edge Case

src/lamp_py/migrations/versions/performance_manager_dev/009_36e7a7aee148_upgrade_sequence.py, src/lamp_py/migrations/versions/performance_manager_prod/006_36e7a7aee148_upgrade_sequence.py, src/lamp_py/migrations/versions/performance_manager_staging/010_36e7a7aee148_upgrade_sequence.py, src/lamp_py/postgres/rail_performance_manager_schema.py
Staging started throwing errors because the pm_event_id column ran out of integer numbers.
This change updates the pm_event_id columns from int to bigint so we don't run out of keys.
=> FIX: Upgrade pm_event_id coumns to BIGINT Type

Data_Dictionary.md
Added bus performance data dict to Data_Dictionary.md for OPMI team to better understand the columns and distinguish between GTFS and LAMP Calculated Values. 
Asana Task: [<asana_ticket_url>](https://app.asana.com/0/1205827492903547/1209285127534394)
=> add bus performance data dict

Data_Dictionary.md, src/lamp_py/bus_performance_manager/events_gtfs_rt.py, src/lamp_py/bus_performance_manager/events_joined.py, src/lamp_py/bus_performance_manager/events_metrics.py, src/lamp_py/bus_performance_manager/events_tm.py, src/lamp_py/runtime_utils/remote_files.py, src/lamp_py/tableau/jobs/bus_performance.py, tests/bus_performance_manager/test_tm_ingestion.py
[Asana Task](https://app.asana.com/0/1189492770004753/1209391790454623)
Save off actual_departure_time, actual_arrival_time, and scheduled_time.
Trigger a regeneration of the whole bus_events datasets by bumping the version.
=> FEAT: Add TransitMaster fields to aid validation of GTFS vs Transitmaster bus data

runners/run_glides_parquet_converter.py, src/lamp_py/tableau/jobs/glides.py
[asana_ticket](https://app.asana.com/0/1205827492903547/1209285127534399/f)
Times are in String HH:MM:SS format, from glides https://mbta.github.io/schemas/events/glides/com.mbta.ctd.glides.trips_updated.v1#time
This is not valid when converted to hyper times. Those have a valid range of 00:00:00 - 24:00:00
https://tableau.github.io/hyper-db/docs/sql/datatype/datetime
Returning back to strings to match existing handling.
=> FIX: Convert Times back to strings to handle when times are greater than midnight

src/lamp_py/tableau/jobs/glides.py
Currently using default which sends them to a OPMI project
=> FIX: Add Glides project_name to hyperjobs to write them to the correct project

poetry.lock, pyproject.toml, src/lamp_py/ingestion/convert_gtfs_rt.py, src/lamp_py/ingestion/converter.py, src/lamp_py/ingestion/ingest_gtfs.py, src/lamp_py/ingestion/light_rail_gps.py, src/lamp_py/ingestion/pipeline.py, src/lamp_py/ingestion/utils.py
[📦 Store dev GTFS-RT data in LAMP 2 - incoming -> springboard](https://app.asana.com/0/1205827492903547/1209390211052912/f)
This set of changes following #493 are to get the Dev ingestion job running on backlog data to have the same memory characteristics and performance as the processing on Prod. 
The specific changes made are: 
- add devgreen tripupdates and vehicleposition inputs to be processed by ingestion and published to springboard (the original task...)
- clear out /tmp folder on restart now that the volume persists to eliminate side effects
- **_critically_** fixed bug where light rail gps files were processed at a rate of 5000 per iteration even when the main ingestion loop was grabbing 250k. This resulted in light rail gps files dominating subsequent list calls, reducing the …
=> FIX: Ingestion processing changes to enable process of backlog 

src/lamp_py/migrations/versions/performance_manager_prod/007_da8f80a3dd90_upgrade_sequence.py
This is a migration for the performance_manager_prod RDS that will REINDEX all indexes to hopefully resolve query recent query degradation. 
This migration also attempts to install the `pgstattuple` on the DB to hopefully retrieve index statistics in the future.
=> FIX: REINDEX PROD performance_manager tables

src/lamp_py/migrations/versions/performance_manager_prod/007_da8f80a3dd90_upgrade_sequence.py
db user does not have permission to create extension, so dropped that.
Run REINDEX inside of sa.text.
=> FIX: Run migration with sa.text

src/lamp_py/ingestion/pipeline.py
light rail gps is failing and crashing ingestion. temporary disable while we investigate and triage. 
nobody uses this yet, so it doesn't hurt anyone
=> (temp) light rail gps is failing ingestion. this is unused, disabling for now

src/lamp_py/ingestion/convert_gtfs_rt.py, src/lamp_py/performance_manager/l0_gtfs_rt_events.py, src/lamp_py/performance_manager/l1_cte_statements.py, src/lamp_py/performance_manager/l1_rt_trips.py, src/lamp_py/postgres/postgres_utils.py, tests/performance_manager/test_backup_trips_match.py, tests/performance_manager/test_performance_manager.py, tests/performance_manager/test_static_trips_subquery.py
Cleanup and fixes for the polars reimplementation of database queries for `backup_rt_static_trip_match`
We were unable to test these changes until getting the previous PR to staging. These changes fix the remaining issues found. 
Mostly datatype issues, one was an issue with polars -> pandas converting a column to float.
=> (fix) update polars types to match database types for vehicle_trips 

src/lamp_py/tableau/jobs/bus_performance.py, src/lamp_py/tableau/jobs/gtfs_rail.py, src/lamp_py/tableau/jobs/rt_rail.py
Rail Performance Manager was dangerously close to OOM, and fell over once in the time window I was observing. Setting these params reduce memory pressure significantly.
=> (feat/mem) set batch_readahead and fragment_readahead for all intensive to_batches() calls

src/lamp_py/runtime_utils/remote_files.py, src/lamp_py/tableau/conversions/convert_bus_performance_data.py, src/lamp_py/tableau/jobs/bus_performance.py, tests/bus_performance_manager/test_bus_convert_for_tableau.py
[Ticket](https://app.asana.com/1/15492006741476/project/1189492770004753/task/1210404550176784?focus=true)
Originally planned on just using the .parquet, but without the timestamp conversion, and the rollup for the recent 7 days, it did not satisfy analyst requirements. Regenerating bus data to enable analysis.
=> (feat) regenerate bus data - add new fields to output rollup

src/lamp_py/tableau/jobs/bus_performance.py
Temporary/Bus all needs to be split up as it is becoming unwieldy to query in Tableau uncompressed. 
Lowering limit to 1 year temporarily while we are still in development of the Bus Performance Manager metrics. 
Will be implemented in this [ticket](https://app.asana.com/1/15492006741476/project/1189492770004753/task/1210469663680236?focus=true)
Undo task: change YEAR for bus all to ALL (split up files)
=> (fix/temp) limit BUS_ALL to 1 year temporarily

src/lamp_py/ingestion_tm/jobs/parition_table.py
correct pyarrow type for schema for timestamp
=> (fix) correct type for message_timestamp

src/lamp_py/tableau/jobs/filtered_hyper.py
Change the end date to today so the FilteredHyperJob updates tableau hourly including today. In support of Recent 7 day LR Vehicle positions for OPMI
Results in some minor contention with ingestion writing - will reevaluate in a future task. [task](https://app.asana.com/1/15492006741476/project/1189492770004753/task/1210680469623771?focus=true)
=> (fix/tableau) change end date to the current day

README.md
https://app.asana.com/1/15492006741476/project/1210964140773280/task/1210979933163701?focus=true
The root README includes overlapping directions which are either redundant or in disagreement. One example is the duplicate instructions for AWS credentials.
1. Repository Design
2. Tests
1. Getting Started by splitting the section into prereqs (which can be done in any order and have their own set of installation instructions), `poetry` configuration, and Checks. I hope this will make it easier to onboard and know when a successful run of LAMP happens
2. Consolidate Dependencies and Getting Started
I ran these instructions and they worked for me with a totally clean MacBook.
1. Is the AWS Credential section clear?
---
- To see the specific tasks where the Asana app for GitHub is being used, …
=> Consolidate local development instructions on README

src/lamp_py/runtime_utils/process_logger.py, tests/runtime_utils/test_process_logger.py
In the course of writing dataframely exceptions, I realized that `ProcessLogger` assumes that:
1. The logger has not only been initalized but also started
2. Exceptions that are logged are also raised
3. We want to start the logger whenever we initialize it with metadata
I don't see the need for either of these assumptions:
1. `.log_start()` takes no arguments (and, thus, no additional information)
2. Inline comments [suggest](https://github.com/mbta/lamp/blob/638fa4f86e420c26a8bb8e47a8e96863bfbe9841/src/lamp_py/runtime_utils/process_logger.py#L124) that unraised exceptions are okay)
3. Assuming that functions always try to log some event (eg. by invoking `log_start`, `log_failure`, `log_complete`, `add_metadata`), then the init is redundant.
Following the spirit of …
=> Make ProcessLogger harder to break

.github/workflows/change_task_count.yaml, src/lamp_py/ad_hoc/pipeline.py, src/lamp_py/ad_hoc/runner_002.py
Asana Task: [ticket](https://app.asana.com/1/15492006741476/project/1189492770004753/task/1211489310804333?focus=true)
**There are no production LAMP application effects from this PR**
Request to extract CR performance data from database, which is currently not output in performance data files
- change filter to be `route_type == 2` to get CR
- change output location
- copy flat file write code into the adhoc-specific methods
This can only be run via the adhoc runner job. 
Adhoc - no validation. verified via notebook CR data extracted as expected
1. Can we come up with a simpler way to do this without rewriting all our queries? I think maybe not, until we do our RPM refactor to remove the DB.
=> feat(rail): adhoc commuter rail performance extract runner
